/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Auth.SubAuth;

import Auth.FrameAuth;
import java.awt.Insets;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelForgotPassword extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    private FrameAuth frame;

    public PanelForgotPassword(FrameAuth frame) {
        initComponents();
        this.frame = frame;
        tUsername.putClientProperty("JTextField.padding", new Insets(0, 8, 0, 0));
        txtPassword.putClientProperty("JTextField.padding", new Insets(0, 8, 0, 0));
        txtConfirmPassword.putClientProperty("JTextField.padding", new Insets(0, 8, 0, 0));
        tInputCaptcha.putClientProperty("JTextField.padding", new Insets(0, 8, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblGarisPemisah = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelCombo = new javax.swing.JPanel();
        lblIconLogin = new javax.swing.JLabel();
        cbLogin = new javax.swing.JComboBox<>();
        panelUsername = new javax.swing.JPanel();
        lblIconUsername = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lblIconPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnShowPassword = new javax.swing.JButton();
        panelConfirmPassword = new javax.swing.JPanel();
        lblIconConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnShowConfirmPassword = new javax.swing.JButton();
        lblKodeCaptcha = new javax.swing.JLabel();
        tInputCaptcha = new javax.swing.JTextField();
        btnSimpanPerubahan = new javax.swing.JButton();
        lblUndo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(580, 533));
        setLayout(new java.awt.BorderLayout());

        panelContent.setBackground(new java.awt.Color(253, 247, 242));
        panelContent.setLayout(new java.awt.GridBagLayout());

        panelCenter.setBackground(new java.awt.Color(253, 247, 242));
        panelCenter.setMaximumSize(new java.awt.Dimension(580, 533));
        panelCenter.setMinimumSize(new java.awt.Dimension(580, 533));
        panelCenter.setPreferredSize(new java.awt.Dimension(580, 533));

        panelHeader.setBackground(new java.awt.Color(253, 247, 242));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(96, 60, 17));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LUPA PASSWORD");
        lblTitle.setAlignmentX(0.5F);

        lblGarisPemisah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGarisPemisah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N
        lblGarisPemisah.setAlignmentX(0.5F);

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(124, 101, 82));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Masukkan Password Baru");
        lblSubTitle.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblTitle))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblGarisPemisah))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblSubTitle)))
                .addGap(169, 169, 169))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(0, 0, 0)
                .addComponent(lblGarisPemisah)
                .addGap(0, 0, 0)
                .addComponent(lblSubTitle))
        );

        panelBody.setBackground(new java.awt.Color(253, 247, 242));

        panelCombo.setBackground(new java.awt.Color(253, 247, 242));
        panelCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelCombo.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-drop-down-30.png"))); // NOI18N

        cbLogin.setBackground(new java.awt.Color(253, 247, 242));
        cbLogin.setForeground(new java.awt.Color(124, 101, 82));
        cbLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Opsi Referensi!", "Username", "Email", "WhatshApp" }));
        cbLogin.setBorder(null);
        cbLogin.addActionListener(this::cbLoginActionPerformed);

        javax.swing.GroupLayout panelComboLayout = new javax.swing.GroupLayout(panelCombo);
        panelCombo.setLayout(panelComboLayout);
        panelComboLayout.setHorizontalGroup(
            panelComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelComboLayout.setVerticalGroup(
            panelComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbLogin)
                    .addGroup(panelComboLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblIconLogin)))
                .addContainerGap())
        );

        panelUsername.setBackground(new java.awt.Color(253, 247, 242));
        panelUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelUsername.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-customer-30.png"))); // NOI18N

        tUsername.setBackground(new java.awt.Color(253, 247, 242));
        tUsername.setForeground(new java.awt.Color(204, 204, 204));
        tUsername.setBorder(null);

        javax.swing.GroupLayout panelUsernameLayout = new javax.swing.GroupLayout(panelUsername);
        panelUsername.setLayout(panelUsernameLayout);
        panelUsernameLayout.setHorizontalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername)
                .addContainerGap())
        );
        panelUsernameLayout.setVerticalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tUsername)
                    .addGroup(panelUsernameLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblIconUsername)))
                .addContainerGap())
        );

        panelPassword.setBackground(new java.awt.Color(253, 247, 242));
        panelPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelPassword.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-password-30.png"))); // NOI18N

        txtPassword.setBackground(new java.awt.Color(253, 247, 242));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);

        btnShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-invisible-20.png"))); // NOI18N
        btnShowPassword.setBorderPainted(false);
        btnShowPassword.setContentAreaFilled(false);

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowPassword)
                .addGap(9, 9, 9))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword)
                            .addComponent(lblIconPassword))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelConfirmPassword.setBackground(new java.awt.Color(253, 247, 242));
        panelConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelConfirmPassword.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconConfirmPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-password-30.png"))); // NOI18N

        txtConfirmPassword.setBackground(new java.awt.Color(253, 247, 242));
        txtConfirmPassword.setText("Konfirmasi Password");
        txtConfirmPassword.setBorder(null);

        btnShowConfirmPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-invisible-20.png"))); // NOI18N
        btnShowConfirmPassword.setBorderPainted(false);
        btnShowConfirmPassword.setContentAreaFilled(false);

        javax.swing.GroupLayout panelConfirmPasswordLayout = new javax.swing.GroupLayout(panelConfirmPassword);
        panelConfirmPassword.setLayout(panelConfirmPasswordLayout);
        panelConfirmPasswordLayout.setHorizontalGroup(
            panelConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowConfirmPassword)
                .addGap(9, 9, 9))
        );
        panelConfirmPasswordLayout.setVerticalGroup(
            panelConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelConfirmPasswordLayout.createSequentialGroup()
                        .addGroup(panelConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtConfirmPassword)
                            .addComponent(lblIconConfirmPassword))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblKodeCaptcha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKodeCaptcha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKodeCaptcha.setText("Kode Captcha");
        lblKodeCaptcha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));

        tInputCaptcha.setBackground(new java.awt.Color(253, 247, 242));
        tInputCaptcha.setForeground(new java.awt.Color(124, 101, 82));
        tInputCaptcha.setText("Masukkan Captcha");
        tInputCaptcha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        tInputCaptcha.setMargin(new java.awt.Insets(2, 10, 2, 6));

        btnSimpanPerubahan.setBackground(new java.awt.Color(96, 60, 17));
        btnSimpanPerubahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpanPerubahan.setForeground(new java.awt.Color(201, 160, 160));
        btnSimpanPerubahan.setText("Simpan Perubahan");
        btnSimpanPerubahan.setBorderPainted(false);

        lblUndo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-undo-28.png"))); // NOI18N
        lblUndo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 60, 17)));
        lblUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUndoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addComponent(lblUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpanPerubahan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(panelUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(panelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(panelConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addGroup(panelBodyLayout.createSequentialGroup()
                                .addComponent(lblKodeCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tInputCaptcha)))
                        .addGap(62, 62, 62))))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKodeCaptcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tInputCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpanPerubahan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lblUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCenterLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCenterLayout.createSequentialGroup()
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 414, Short.MAX_VALUE)))
        );

        panelContent.add(panelCenter, new java.awt.GridBagConstraints());

        add(panelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoginActionPerformed

    private void lblUndoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUndoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUndoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowConfirmPassword;
    private javax.swing.JButton btnShowPassword;
    private javax.swing.JButton btnSimpanPerubahan;
    private javax.swing.JComboBox<String> cbLogin;
    private javax.swing.JLabel lblGarisPemisah;
    private javax.swing.JLabel lblIconConfirmPassword;
    private javax.swing.JLabel lblIconLogin;
    private javax.swing.JLabel lblIconPassword;
    private javax.swing.JLabel lblIconUsername;
    private javax.swing.JLabel lblKodeCaptcha;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUndo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCombo;
    private javax.swing.JPanel panelConfirmPassword;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JTextField tInputCaptcha;
    private javax.swing.JTextField tUsername;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
