/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Auth.SubAuth;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelMaintenance_1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelMaintenance
     */
    public PanelMaintenance_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new javax.swing.JPanel();
        lblIconMaintenance = new javax.swing.JLabel();
        lblPadiKanan = new javax.swing.JLabel();
        lblPadiKiri = new javax.swing.JLabel();
        lblShadow = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblGarisPemisah1 = new javax.swing.JLabel();
        lblGarisPemisah2 = new javax.swing.JLabel();
        lblMaintenanceFitur = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        panelBawah = new javax.swing.JPanel();
        btnKembaliKe = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(590, 533));
        setLayout(new java.awt.BorderLayout());

        panelAtas.setBackground(new java.awt.Color(253, 247, 242));
        panelAtas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Icon Maintenance.png"))); // NOI18N
        panelAtas.add(lblIconMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 12, -1, -1));

        lblPadiKanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Padi Kanan.png"))); // NOI18N
        panelAtas.add(lblPadiKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 12, -1, -1));

        lblPadiKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Padi Kiri.png"))); // NOI18N
        panelAtas.add(lblPadiKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 12, -1, -1));

        lblShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Shadow.png"))); // NOI18N
        panelAtas.add(lblShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 18, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(96, 60, 17));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MAINTENANCE");
        panelAtas.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 24, -1, -1));

        lblGarisPemisah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N
        panelAtas.add(lblGarisPemisah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 78, -1, 20));

        lblGarisPemisah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N
        panelAtas.add(lblGarisPemisah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 160, -1, 20));

        lblMaintenanceFitur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenanceFitur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaintenanceFitur.setText("<html><center>Fitur <b>Default</b> sedang dalam<br>Tahap pengembangan.</center></html>");
        panelAtas.add(lblMaintenanceFitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 104, 310, 50));

        lblDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeskripsi.setText("<html><center>Kami sedang mempersiapkan <br>Pengalaman terbaik untuk<br>Anda.</center></html>");
        panelAtas.add(lblDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 186, 210, -1));

        add(panelAtas, java.awt.BorderLayout.CENTER);

        panelBawah.setBackground(new java.awt.Color(253, 247, 242));

        btnKembaliKe.setBackground(new java.awt.Color(96, 60, 17));
        btnKembaliKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembaliKe.setForeground(new java.awt.Color(201, 160, 160));
        btnKembaliKe.setText("Kembali Ke");

        javax.swing.GroupLayout panelBawahLayout = new javax.swing.GroupLayout(panelBawah);
        panelBawah.setLayout(panelBawahLayout);
        panelBawahLayout.setHorizontalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBawahLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnKembaliKe, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBawahLayout.setVerticalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembaliKe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(panelBawah, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembaliKe;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblGarisPemisah1;
    private javax.swing.JLabel lblGarisPemisah2;
    private javax.swing.JLabel lblIconMaintenance;
    private javax.swing.JLabel lblMaintenanceFitur;
    private javax.swing.JLabel lblPadiKanan;
    private javax.swing.JLabel lblPadiKiri;
    private javax.swing.JLabel lblShadow;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBawah;
    // End of variables declaration//GEN-END:variables
}
