/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Auth.SubAuth;

import Auth.FrameAuth;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelUbahEmail_1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelUbahEmail
     */
    private FrameAuth frame;

    public PanelUbahEmail_1(FrameAuth frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblGarisPemisah1 = new javax.swing.JLabel();
        lblSubTitle1 = new javax.swing.JLabel();
        lblUndo = new javax.swing.JLabel();
        panelContent1 = new javax.swing.JPanel();
        panelBody1 = new javax.swing.JPanel();
        panelEmailLama1 = new javax.swing.JPanel();
        lblIconLama1 = new javax.swing.JLabel();
        tEmailLama1 = new javax.swing.JTextField();
        panelEmailBaru1 = new javax.swing.JPanel();
        lblIconEmailBaru1 = new javax.swing.JLabel();
        tEmailBaru1 = new javax.swing.JTextField();
        panelConfirmEmail1 = new javax.swing.JPanel();
        lblIconConfirmEmail1 = new javax.swing.JLabel();
        tConfirmEmail1 = new javax.swing.JTextField();
        panelWarning1 = new javax.swing.JPanel();
        lblIconWarning1 = new javax.swing.JLabel();
        panelTextWatning1 = new javax.swing.JPanel();
        lblTextWarning1 = new javax.swing.JLabel();
        btnSimpan1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(580, 533));
        setLayout(new java.awt.BorderLayout());

        panelHeader1.setBackground(new java.awt.Color(253, 247, 242));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(96, 60, 17));
        lblTitle1.setText("UBAH EMAIL AKUN");

        lblGarisPemisah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N

        lblSubTitle1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTitle1.setForeground(new java.awt.Color(124, 101, 82));
        lblSubTitle1.setText("Perbarui Almaat Email Akun Anda!");

        lblUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-undo-28.png"))); // NOI18N
        lblUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUndoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHeader1Layout = new javax.swing.GroupLayout(panelHeader1);
        panelHeader1.setLayout(panelHeader1Layout);
        panelHeader1Layout.setHorizontalGroup(
            panelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeader1Layout.createSequentialGroup()
                .addGroup(panelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeader1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUndo)
                        .addGap(143, 143, 143)
                        .addComponent(lblTitle1))
                    .addGroup(panelHeader1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblGarisPemisah1))
                    .addGroup(panelHeader1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblSubTitle1)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        panelHeader1Layout.setVerticalGroup(
            panelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeader1Layout.createSequentialGroup()
                .addGroup(panelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeader1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitle1))
                    .addGroup(panelHeader1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUndo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGarisPemisah1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelHeader1, java.awt.BorderLayout.NORTH);

        panelContent1.setLayout(new java.awt.BorderLayout());

        panelBody1.setBackground(new java.awt.Color(253, 247, 242));

        panelEmailLama1.setBackground(new java.awt.Color(253, 247, 242));
        panelEmailLama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelEmailLama1.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconLama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-email-30.png"))); // NOI18N

        tEmailLama1.setBackground(new java.awt.Color(253, 247, 242));
        tEmailLama1.setForeground(new java.awt.Color(204, 204, 204));
        tEmailLama1.setText("Email Lama");
        tEmailLama1.setBorder(null);
        tEmailLama1.addActionListener(this::tEmailLama1ActionPerformed);

        javax.swing.GroupLayout panelEmailLama1Layout = new javax.swing.GroupLayout(panelEmailLama1);
        panelEmailLama1.setLayout(panelEmailLama1Layout);
        panelEmailLama1Layout.setHorizontalGroup(
            panelEmailLama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmailLama1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconLama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tEmailLama1)
                .addContainerGap())
        );
        panelEmailLama1Layout.setVerticalGroup(
            panelEmailLama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmailLama1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmailLama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tEmailLama1)
                    .addGroup(panelEmailLama1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblIconLama1)))
                .addContainerGap())
        );

        panelEmailBaru1.setBackground(new java.awt.Color(253, 247, 242));
        panelEmailBaru1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelEmailBaru1.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconEmailBaru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-email-30.png"))); // NOI18N

        tEmailBaru1.setBackground(new java.awt.Color(253, 247, 242));
        tEmailBaru1.setForeground(new java.awt.Color(204, 204, 204));
        tEmailBaru1.setText("Email Baru");
        tEmailBaru1.setBorder(null);

        javax.swing.GroupLayout panelEmailBaru1Layout = new javax.swing.GroupLayout(panelEmailBaru1);
        panelEmailBaru1.setLayout(panelEmailBaru1Layout);
        panelEmailBaru1Layout.setHorizontalGroup(
            panelEmailBaru1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmailBaru1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconEmailBaru1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tEmailBaru1)
                .addContainerGap())
        );
        panelEmailBaru1Layout.setVerticalGroup(
            panelEmailBaru1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmailBaru1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmailBaru1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tEmailBaru1)
                    .addGroup(panelEmailBaru1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblIconEmailBaru1)))
                .addContainerGap())
        );

        panelConfirmEmail1.setBackground(new java.awt.Color(253, 247, 242));
        panelConfirmEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 94, 60)));
        panelConfirmEmail1.setPreferredSize(new java.awt.Dimension(42, 45));

        lblIconConfirmEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-email-30.png"))); // NOI18N

        tConfirmEmail1.setBackground(new java.awt.Color(253, 247, 242));
        tConfirmEmail1.setForeground(new java.awt.Color(204, 204, 204));
        tConfirmEmail1.setText("Konfirmasi Email Baru");
        tConfirmEmail1.setBorder(null);
        tConfirmEmail1.addActionListener(this::tConfirmEmail1ActionPerformed);

        javax.swing.GroupLayout panelConfirmEmail1Layout = new javax.swing.GroupLayout(panelConfirmEmail1);
        panelConfirmEmail1.setLayout(panelConfirmEmail1Layout);
        panelConfirmEmail1Layout.setHorizontalGroup(
            panelConfirmEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmEmail1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconConfirmEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tConfirmEmail1)
                .addContainerGap())
        );
        panelConfirmEmail1Layout.setVerticalGroup(
            panelConfirmEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfirmEmail1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfirmEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tConfirmEmail1)
                    .addGroup(panelConfirmEmail1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblIconConfirmEmail1)))
                .addContainerGap())
        );

        panelWarning1.setBackground(new java.awt.Color(234, 222, 207));

        lblIconWarning1.setBackground(new java.awt.Color(253, 247, 242));
        lblIconWarning1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconWarning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-warning-30.png"))); // NOI18N

        panelTextWatning1.setBackground(new java.awt.Color(234, 222, 207));

        lblTextWarning1.setBackground(new java.awt.Color(234, 222, 207));
        lblTextWarning1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextWarning1.setForeground(new java.awt.Color(96, 60, 17));
        lblTextWarning1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextWarning1.setText("<html>Pastikan Email yang Anda masukkan aktif.<br>Email baru akan digunakan untuk login <br>dan menerima notifikasi.</html>");
        lblTextWarning1.setAutoscrolls(true);

        javax.swing.GroupLayout panelTextWatning1Layout = new javax.swing.GroupLayout(panelTextWatning1);
        panelTextWatning1.setLayout(panelTextWatning1Layout);
        panelTextWatning1Layout.setHorizontalGroup(
            panelTextWatning1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTextWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelTextWatning1Layout.setVerticalGroup(
            panelTextWatning1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextWatning1Layout.createSequentialGroup()
                .addComponent(lblTextWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelWarning1Layout = new javax.swing.GroupLayout(panelWarning1);
        panelWarning1.setLayout(panelWarning1Layout);
        panelWarning1Layout.setHorizontalGroup(
            panelWarning1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarning1Layout.createSequentialGroup()
                .addComponent(lblIconWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTextWatning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelWarning1Layout.setVerticalGroup(
            panelWarning1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTextWatning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblIconWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnSimpan1.setBackground(new java.awt.Color(96, 60, 17));
        btnSimpan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(201, 160, 160));
        btnSimpan1.setText("Simpan Perubahan");
        btnSimpan1.setBorderPainted(false);

        javax.swing.GroupLayout panelBody1Layout = new javax.swing.GroupLayout(panelBody1);
        panelBody1.setLayout(panelBody1Layout);
        panelBody1Layout.setHorizontalGroup(
            panelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBody1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEmailLama1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(panelEmailBaru1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(panelConfirmEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(panelWarning1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        panelBody1Layout.setVerticalGroup(
            panelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBody1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEmailLama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEmailBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConfirmEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelContent1.add(panelBody1, java.awt.BorderLayout.CENTER);

        add(panelContent1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tEmailLama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailLama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailLama1ActionPerformed

    private void tConfirmEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tConfirmEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tConfirmEmail1ActionPerformed

    private void lblUndoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUndoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUndoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JLabel lblGarisPemisah1;
    private javax.swing.JLabel lblIconConfirmEmail1;
    private javax.swing.JLabel lblIconEmailBaru1;
    private javax.swing.JLabel lblIconLama1;
    private javax.swing.JLabel lblIconWarning1;
    private javax.swing.JLabel lblSubTitle1;
    private javax.swing.JLabel lblTextWarning1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUndo;
    private javax.swing.JPanel panelBody1;
    private javax.swing.JPanel panelConfirmEmail1;
    private javax.swing.JPanel panelContent1;
    private javax.swing.JPanel panelEmailBaru1;
    private javax.swing.JPanel panelEmailLama1;
    private javax.swing.JPanel panelHeader1;
    private javax.swing.JPanel panelTextWatning1;
    private javax.swing.JPanel panelWarning1;
    private javax.swing.JTextField tConfirmEmail1;
    private javax.swing.JTextField tEmailBaru1;
    private javax.swing.JTextField tEmailLama1;
    // End of variables declaration//GEN-END:variables
}
