/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Loading;

import App.AppTheme;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class FrameLoading extends javax.swing.JFrame {

    private String fitur;
    private Runnable selesaiLoading;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLoading.class.getName());

    /**
     * Creates new form FrameLoading
     */
    public FrameLoading(String fitur, Runnable selesaiLoading) {
        AppTheme.applyThemeAuth();
        initComponents();
        this.fitur = fitur;
        this.selesaiLoading = selesaiLoading;
        setLocationRelativeTo(null);
    }

    public void mulaiLoading() {

        new Thread(() -> {

            try {

                for (int i = 0; i <= 100; i++) {

                    final int progress = i;

                    SwingUtilities.invokeLater(() -> {

                        progressBar.setValue(progress);
                        lblPersentase.setText(progress + "%");

                        if (progress < 30) {
                            lblStatus.setText("Memverifikasi " + fitur + "...");
                        } else if (progress < 60) {
                            lblStatus.setText("Menghubungkan database...");
                        } else if (progress < 90) {
                            lblStatus.setText("Menyiapkan " + fitur + "...");
                        } else {
                            lblStatus.setText(fitur + " berhasil.");
                        }

                    });

                    Thread.sleep(30);

                }

                SwingUtilities.invokeLater(() -> {

                    if (selesaiLoading != null) {
                        selesaiLoading.run();
                    }

                    dispose();

                });

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());

            }

        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoading = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jsGarisPemisah = new javax.swing.JSeparator();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblPersentase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Loading");
        setUndecorated(true);

        panelLoading.setBackground(new java.awt.Color(96, 60, 17));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LOADING...");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(245, 230, 211));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Memverifikasi akun...");

        progressBar.setBackground(new java.awt.Color(212, 180, 131));
        progressBar.setForeground(new java.awt.Color(255, 255, 255));
        progressBar.setPreferredSize(new java.awt.Dimension(350, 25));

        lblPersentase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPersentase.setForeground(new java.awt.Color(230, 199, 156));
        lblPersentase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersentase.setText("0%");

        javax.swing.GroupLayout panelLoadingLayout = new javax.swing.GroupLayout(panelLoading);
        panelLoading.setLayout(panelLoadingLayout);
        panelLoadingLayout.setHorizontalGroup(
            panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
            .addGroup(panelLoadingLayout.createSequentialGroup()
                .addGroup(panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoadingLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jsGarisPemisah, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoadingLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoadingLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lblPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelLoadingLayout.setVerticalGroup(
            panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadingLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jsGarisPemisah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrameLoading().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jsGarisPemisah;
    private javax.swing.JLabel lblPersentase;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelLoading;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
