/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Master;

import App.AppTheme;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import javax.swing.BorderFactory;
import java.awt.CardLayout;
import Screens.Master.SubMaster.PanelDashboard;
import Screens.Master.SubMaster.PanelDataProduk;
import Screens.Master.SubMaster.PanelDataSupplier;
import Screens.Master.SubMaster.PanelBarangMasuk;
import Screens.Master.SubMaster.PanelSetting;
import Screens.Master.SubMaster.PanelAbout;
import javax.swing.JPanel;
import Screens.Loading.FrameLoading;
import java.awt.CardLayout;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class FrameMaster extends javax.swing.JFrame {

    private CardLayout card = new CardLayout();
    private final Color WARNA_DEFAULT = new Color(106, 72, 46);   // Coklat sekarang
    private final Color WARNA_AKTIF = new Color(129, 90, 58);   // Sedikit lebih terang
    private final Color WARNA_HOVER = new Color(118, 82, 52);   // Hover
    private final Color MENU = new Color(106, 67, 38);
    private final Color ACTIVE = new Color(128, 86, 54);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMaster.class.getName());

    /**
     * Creates new form FrameMaster
     */
    public FrameMaster() {
        AppTheme.applyThemeAuth();
        initComponents();
        initMenu();
        styleMenu(btnDashboard);
        styleMenu(btnDataProduk);
        styleMenu(btnDataSupplier);
        styleMenu(btnBarangMasuk);
        styleMenu(btnAbout);
        styleMenu(btnBarangKeluar);
        styleMenu(btnLaporan);
        styleMenu(btnSetting);
        styleMenu(btnLogout);
        panelContent.setLayout(card);
        panelContent.add(new PanelDashboard(), "dashboard");
        panelContent.add(new PanelDataProduk(), "produk");
        panelContent.add(new PanelDataSupplier(), "supplier");
        panelContent.add(new PanelBarangMasuk(), "barangmasuk");
        panelContent.add(new PanelSetting(), "setting");
        panelContent.add(new PanelAbout(), "about");

        card.show(panelContent, "dashboard");
    }

    private void initMenu() {
        hoverMenu(btnDashboard);
        hoverMenu(btnDataProduk);
        hoverMenu(btnDataSupplier);
        hoverMenu(btnBarangMasuk);
        hoverMenu(btnBarangKeluar);
        hoverMenu(btnLaporan);
        hoverMenu(btnSetting);
        hoverMenu(btnAbout);
        hoverMenu(btnLogout);
    }

    private void styleMenu(JButton btn) {
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setVerticalAlignment(SwingConstants.CENTER);

        btn.setHorizontalTextPosition(SwingConstants.RIGHT);
        btn.setVerticalTextPosition(SwingConstants.CENTER);

        btn.setIconTextGap(18);

        // Padding kiri dan kanan
        btn.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));

        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
    }

    private void resetMenu() {

        panelDashboard.setBackground(MENU);
        panelDataProduk.setBackground(MENU);
        panelSupplier.setBackground(MENU);
        panelBarangMasuk.setBackground(MENU);
        panelBarangKeluar.setBackground(MENU);
        panelLaporan.setBackground(MENU);
        panelSetting.setBackground(MENU);
        panelAbout.setBackground(MENU);
        panelLogout.setBackground(MENU);

    }

    private void menuAktif(JPanel panel) {

        resetMenu();
        panel.setBackground(ACTIVE);

    }

    private void hoverMenu(JButton btn) {

        btn.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {

                if (btn.getBackground().equals(WARNA_DEFAULT)) {
                    btn.setBackground(WARNA_HOVER);
                }

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {

                if (btn.getBackground().equals(WARNA_HOVER)) {
                    btn.setBackground(WARNA_DEFAULT);
                }

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelSubMenu = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelDataProduk = new javax.swing.JPanel();
        btnDataProduk = new javax.swing.JButton();
        panelSupplier = new javax.swing.JPanel();
        btnDataSupplier = new javax.swing.JButton();
        panelBarangMasuk = new javax.swing.JPanel();
        btnBarangMasuk = new javax.swing.JButton();
        panelBarangKeluar = new javax.swing.JPanel();
        btnBarangKeluar = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLaporan = new javax.swing.JButton();
        panelSetting = new javax.swing.JPanel();
        btnSetting = new javax.swing.JButton();
        panelAbout = new javax.swing.JPanel();
        btnAbout = new javax.swing.JButton();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hijabella Collection");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelUtama.setPreferredSize(new java.awt.Dimension(1280, 720));
        panelUtama.setLayout(new java.awt.BorderLayout());

        panelKiri.setPreferredSize(new java.awt.Dimension(250, 720));
        panelKiri.setLayout(new java.awt.BorderLayout());

        panelLogo.setBackground(new java.awt.Color(96, 60, 17));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Logo.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKiri.add(panelLogo, java.awt.BorderLayout.PAGE_START);

        panelMenu.setLayout(new java.awt.BorderLayout());

        panelSubMenu.setBackground(new java.awt.Color(96, 60, 17));

        panelDashboard.setBackground(new java.awt.Color(96, 60, 17));
        panelDashboard.setLayout(new java.awt.BorderLayout());

        btnDashboard.setBackground(new java.awt.Color(96, 60, 17));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-beranda-26.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setIconTextGap(10);
        btnDashboard.setPreferredSize(new java.awt.Dimension(81, 30));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        panelDashboard.add(btnDashboard, java.awt.BorderLayout.CENTER);

        panelDataProduk.setBackground(new java.awt.Color(96, 60, 17));
        panelDataProduk.setLayout(new java.awt.BorderLayout());

        btnDataProduk.setBackground(new java.awt.Color(96, 60, 17));
        btnDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataProduk.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-data-produk-26.png"))); // NOI18N
        btnDataProduk.setText("Data Produk");
        btnDataProduk.setBorderPainted(false);
        btnDataProduk.setIconTextGap(10);
        btnDataProduk.setPreferredSize(new java.awt.Dimension(81, 30));
        btnDataProduk.addActionListener(this::btnDataProdukActionPerformed);
        panelDataProduk.add(btnDataProduk, java.awt.BorderLayout.CENTER);

        panelSupplier.setBackground(new java.awt.Color(96, 60, 17));
        panelSupplier.setLayout(new java.awt.BorderLayout());

        btnDataSupplier.setBackground(new java.awt.Color(96, 60, 17));
        btnDataSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataSupplier.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-data-supplier-26.png"))); // NOI18N
        btnDataSupplier.setText("Data Supplier");
        btnDataSupplier.setBorderPainted(false);
        btnDataSupplier.setIconTextGap(10);
        btnDataSupplier.setPreferredSize(new java.awt.Dimension(81, 30));
        panelSupplier.add(btnDataSupplier, java.awt.BorderLayout.CENTER);

        panelBarangMasuk.setBackground(new java.awt.Color(96, 60, 17));
        panelBarangMasuk.setLayout(new java.awt.BorderLayout());

        btnBarangMasuk.setBackground(new java.awt.Color(96, 60, 17));
        btnBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBarangMasuk.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-masuk-26.png"))); // NOI18N
        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.setBorderPainted(false);
        btnBarangMasuk.setIconTextGap(10);
        btnBarangMasuk.setPreferredSize(new java.awt.Dimension(81, 30));
        btnBarangMasuk.addActionListener(this::btnBarangMasukActionPerformed);
        panelBarangMasuk.add(btnBarangMasuk, java.awt.BorderLayout.CENTER);

        panelBarangKeluar.setBackground(new java.awt.Color(96, 60, 17));
        panelBarangKeluar.setLayout(new java.awt.BorderLayout());

        btnBarangKeluar.setBackground(new java.awt.Color(96, 60, 17));
        btnBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBarangKeluar.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-keluar-26.png"))); // NOI18N
        btnBarangKeluar.setText("Barang Keluar");
        btnBarangKeluar.setBorderPainted(false);
        btnBarangKeluar.setIconTextGap(10);
        btnBarangKeluar.setPreferredSize(new java.awt.Dimension(81, 30));
        panelBarangKeluar.add(btnBarangKeluar, java.awt.BorderLayout.PAGE_START);

        panelLaporan.setBackground(new java.awt.Color(96, 60, 17));
        panelLaporan.setLayout(new java.awt.BorderLayout());

        btnLaporan.setBackground(new java.awt.Color(96, 60, 17));
        btnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(201, 160, 160));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-laporan-26.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorderPainted(false);
        btnLaporan.setIconTextGap(10);
        btnLaporan.setPreferredSize(new java.awt.Dimension(81, 30));
        panelLaporan.add(btnLaporan, java.awt.BorderLayout.CENTER);

        panelSetting.setBackground(new java.awt.Color(96, 60, 17));
        panelSetting.setLayout(new java.awt.BorderLayout());

        btnSetting.setBackground(new java.awt.Color(96, 60, 17));
        btnSetting.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-gerigi-26.png"))); // NOI18N
        btnSetting.setText("Setting");
        btnSetting.setBorderPainted(false);
        btnSetting.setIconTextGap(10);
        btnSetting.setPreferredSize(new java.awt.Dimension(81, 30));
        panelSetting.add(btnSetting, java.awt.BorderLayout.CENTER);

        panelAbout.setBackground(new java.awt.Color(96, 60, 17));
        panelAbout.setLayout(new java.awt.BorderLayout());

        btnAbout.setBackground(new java.awt.Color(96, 60, 17));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-about-26.png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorderPainted(false);
        btnAbout.setIconTextGap(10);
        btnAbout.setPreferredSize(new java.awt.Dimension(81, 30));
        btnAbout.addActionListener(this::btnAboutActionPerformed);
        panelAbout.add(btnAbout, java.awt.BorderLayout.CENTER);

        panelLogout.setBackground(new java.awt.Color(96, 60, 17));
        panelLogout.setLayout(new java.awt.BorderLayout());

        btnLogout.setBackground(new java.awt.Color(96, 60, 17));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(201, 160, 160));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-logout-26.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setIconTextGap(10);
        btnLogout.setPreferredSize(new java.awt.Dimension(81, 30));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        panelLogout.add(btnLogout, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelSubMenuLayout = new javax.swing.GroupLayout(panelSubMenu);
        panelSubMenu.setLayout(panelSubMenuLayout);
        panelSubMenuLayout.setHorizontalGroup(
            panelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDataProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBarangMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSubMenuLayout.setVerticalGroup(
            panelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubMenuLayout.createSequentialGroup()
                .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDataProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        panelMenu.add(panelSubMenu, java.awt.BorderLayout.CENTER);

        panelKiri.add(panelMenu, java.awt.BorderLayout.CENTER);

        panelUtama.add(panelKiri, java.awt.BorderLayout.WEST);

        panelContent.setBackground(new java.awt.Color(250, 245, 241));
        panelContent.setPreferredSize(new java.awt.Dimension(0, 0));
        panelContent.setLayout(new java.awt.CardLayout());
        panelUtama.add(panelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1296, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        card.show(panelContent, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int pilih = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (pilih == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDataProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProdukActionPerformed
        // TODO add your handling code here:
        card.show(panelContent, "produk");
    }//GEN-LAST:event_btnDataProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMaster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBarangKeluar;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataProduk;
    private javax.swing.JButton btnDataSupplier;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelBarangKeluar;
    private javax.swing.JPanel panelBarangMasuk;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelDataProduk;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSetting;
    private javax.swing.JPanel panelSubMenu;
    private javax.swing.JPanel panelSupplier;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
