/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package about;

/**
 *
 * @author lenovo
 */
public class PanelSetting2 extends javax.swing.JPanel {

    /**
     * Creates new form PanelSetting2
     */
    public PanelSetting2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();
        lblIconMaintenance = new javax.swing.JLabel();
        lblPadiKanan = new javax.swing.JLabel();
        lblPadiKiri = new javax.swing.JLabel();
        lblShadow = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblGarisPemisah1 = new javax.swing.JLabel();
        lblGarisPemisah2 = new javax.swing.JLabel();
        lblMaintenanceFitur = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        btnKembaliKe = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(253, 247, 242));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 230));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.GridLayout());

        panelCenter.setBackground(new java.awt.Color(253, 247, 242));
        panelCenter.setMaximumSize(new java.awt.Dimension(580, 533));
        panelCenter.setMinimumSize(new java.awt.Dimension(580, 533));

        panelBody.setBackground(new java.awt.Color(253, 247, 242));

        lblIconMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Icon Maintenance.png"))); // NOI18N

        lblPadiKanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Padi Kanan.png"))); // NOI18N

        lblPadiKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Padi Kiri.png"))); // NOI18N

        lblShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Shadow.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(96, 60, 17));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MAINTENANCE");

        lblGarisPemisah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N

        lblGarisPemisah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah.png"))); // NOI18N

        lblMaintenanceFitur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenanceFitur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaintenanceFitur.setText("<html><center>Fitur <b>Default</b> sedang dalam<br>Tahap pengembangan.</center></html>");

        lblDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeskripsi.setText("<html><center>Kami sedang mempersiapkan <br>Pengalaman terbaik untuk<br>Anda.</center></html>");

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblPadiKiri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIconMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPadiKanan))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblShadow)))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblGarisPemisah1))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblGarisPemisah2))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblMaintenanceFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPadiKanan)
                    .addComponent(lblPadiKiri)
                    .addComponent(lblIconMaintenance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShadow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGarisPemisah1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaintenanceFitur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGarisPemisah2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFooter.setBackground(new java.awt.Color(253, 247, 242));

        btnKembaliKe.setBackground(new java.awt.Color(96, 60, 17));
        btnKembaliKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembaliKe.setForeground(new java.awt.Color(201, 160, 160));
        btnKembaliKe.setText("Kembali Ke");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnKembaliKe, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembaliKe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCenterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel6.add(panelCenter);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, "card2");

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembaliKe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblGarisPemisah1;
    private javax.swing.JLabel lblGarisPemisah2;
    private javax.swing.JLabel lblIconMaintenance;
    private javax.swing.JLabel lblMaintenanceFitur;
    private javax.swing.JLabel lblPadiKanan;
    private javax.swing.JLabel lblPadiKiri;
    private javax.swing.JLabel lblShadow;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelFooter;
    // End of variables declaration//GEN-END:variables
}
