/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package about;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USERR
 */
public class PanelBarangKeluar extends javax.swing.JPanel {

    /**
     * Creates new form panelAbout
     */
    public PanelBarangKeluar() {
        initComponents();
        loadTabelBarangKeluar();
        reset();
        jumlahBarangKeluar();
        totalPenjualanHariIni();
        loadComboBarang();
    }
    
    
    
     void loadTabelBarangKeluar(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID penjualan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal");
        model.addColumn("Keterangan");
        
        String sql = "SELECT * FROM penjualan";
        
        try {
            Connection conn = koneksi.konek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String idPenjualan = rs.getString("id_penjualan");
                String kodeProduk = rs.getString("id_produk");
                String namaProduk = rs.getString("nama_produk");
                String jumlah = rs.getString("jumlah_keluar");
                String tanggal = rs.getString("tanggal_penjualan");
                String keterangan = rs.getString("keterangan");

                Object[] baris = {idPenjualan, kodeProduk, namaProduk, jumlah, tanggal, keterangan};

                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
        tblBarangKeluar.setModel(model);
        
    }
     
     
     void reset(){
         tJumlahKeluar.setText(null);
         tKeterangan.setText(null);
         tIdPenjualan.setText(null);
         tNamaProduk.setText(null);
         
     }
     
     void jumlahBarangKeluar(){
          
             try {
             Connection conn = koneksi.konek();
             String sqlPenjualan = "SELECT COALESCE(SUM(jumlah_keluar),0) AS total_barang " + "FROM penjualan "+"WHERE tanggal_penjualan = CURDATE()";
             Statement psPenjualan = conn.createStatement();
             ResultSet rsPenjualan = psPenjualan.executeQuery(sqlPenjualan);
             if (rsPenjualan.next()) {
                 int jumlah = rsPenjualan.getInt("total_barang");
                 jJumlahPenjualan.setText(String.valueOf(jumlah));
             }
         } catch (SQLException sQLException) {
         }
     }
     
     void totalPenjualanHariIni(){
       
         try {
             Connection conn = koneksi.konek();
             String sqlPenjualan = "SELECT COUNT(*) AS total_penjualan " + "FROM penjualan " + "WHERE tanggal_penjualan = CURDATE()";
             Statement psPenjualan = conn.createStatement();
             ResultSet rsPenjualan = psPenjualan.executeQuery(sqlPenjualan);
             if (rsPenjualan.next()) {
                 int jumlah = rsPenjualan.getInt("total_penjualan");
                 jTotalPenjualan.setText(String.valueOf(jumlah));
             }
         } catch (SQLException sQLException) {
         }
     }
     
     
         void loadComboBarang(){
        try {
            String sql = "SELECT id_produk FROM produk";
            Connection conn = koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            cKodeProduk.removeAllItems();
            while (rs.next()) {
             cKodeProduk.addItem(rs.getString("id_produk"));
            }
        } catch (SQLException e) {
       
                    
        }
    }
   protected void paintCommponent(java.awt.Graphics g){
       g.setColor(getBackground());
       g.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jJumlahPenjualan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTotalPenjualan = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarangKeluar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tIdPenjualan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tNamaProduk = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tJumlahKeluar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tTanggal = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        tKeterangan = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cKodeProduk = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(250, 245, 241));
        setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(250, 245, 241));
        jPanel10.setPreferredSize(new java.awt.Dimension(674, 130));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 245, 241), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185))));
        jPanel11.setPreferredSize(new java.awt.Dimension(674, 45));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Barang Keluar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(831, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(250, 245, 241));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 245, 241), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185))));
        jPanel2.setPreferredSize(new java.awt.Dimension(363, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about/img/iconkeluar (3).jpeg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 50, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 60, 17));
        jLabel5.setText("Total Barang Keluar Hari Ini");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 420, -1));

        jJumlahPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jJumlahPenjualan.setForeground(new java.awt.Color(96, 60, 17));
        jJumlahPenjualan.setText("jLabel6");
        jPanel2.add(jJumlahPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Total Item");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 37));

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 245, 241), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185))));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(96, 60, 17));
        jLabel22.setText("Total Penjualan");

        jTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTotalPenjualan.setForeground(new java.awt.Color(96, 60, 17));
        jTotalPenjualan.setText("jLabel6");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel24.setText("Total Penjualan");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about/img/icons8-basket-40.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTotalPenjualan)
                    .addComponent(jLabel24))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTotalPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(12, 12, 12))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jPanel10.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(250, 245, 241));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 245, 241), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185))));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 434));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.CardLayout());

        tblBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarangKeluar);

        jPanel13.add(jScrollPane2, "card2");

        jPanel5.add(jPanel13, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Riwayat Barang Keluar");
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 245, 241), 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185))));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Catatan Barang Keluar");

        jSeparator1.setForeground(new java.awt.Color(96, 60, 17));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 60, 17));
        jLabel3.setText("ID Penjualan");

        tIdPenjualan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185), 2));

        btnTambah.setBackground(new java.awt.Color(96, 60, 17));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(96, 60, 17));
        jLabel18.setText("Nama Barang");

        tNamaProduk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185), 2));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(96, 60, 17));
        jLabel19.setText("Jumlah Keluar");

        tJumlahKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185), 2));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(96, 60, 17));
        jLabel20.setText("Tanggal");

        tTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185), 2));
        tTanggal.setDateFormatString("yyyy MM dd");
        tTanggal.setMaxSelectableDate(new java.util.Date(253370743281000L));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(96, 60, 17));
        jLabel21.setText("Keterangan");

        tKeterangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 208, 185), 2));

        btnEdit.setBackground(new java.awt.Color(96, 60, 17));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setBackground(new java.awt.Color(96, 60, 17));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 60, 17));
        jLabel11.setText("Kode barang");

        cKodeProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tIdPenjualan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(tNamaProduk)
                    .addComponent(tJumlahKeluar)
                    .addComponent(tKeterangan)
                    .addComponent(tTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel11)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(cKodeProduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tIdPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(cKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tJumlahKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String idPenjualan = tIdPenjualan.getText();
              String kodeProduk = cKodeProduk.getSelectedItem().toString();
        String namaProduk = tNamaProduk.getText();
        java.util.Date tanggalDate = tTanggal.getDate();
        java.sql.Date tanggal = new java.sql.Date(tanggalDate.getTime());
        String jumlah = tJumlahKeluar.getText();
        String keterangan = tKeterangan.getText();
       
        String sql = "INSERT INTO penjualan(id_penjualan, tanggal_penjualan, id_produk, nama_produk, jumlah_keluar, keterangan) VALUES (?,?,?,?,?,?)";
        try {
            Connection conn = koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPenjualan);
            ps.setDate(2, tanggal);
            ps.setString(3,kodeProduk);
            ps.setString(4, namaProduk);
            ps.setString(5 , jumlah);
            ps.setString(6, keterangan);
            
            
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        } catch (HeadlessException headlessException) {
      
        }
        loadTabelBarangKeluar();
    reset();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         String idPenjualan = tIdPenjualan.getText();
         String kodeProduk = cKodeProduk.getSelectedItem().toString();
        String namaProduk = tNamaProduk.getText();
         java.util.Date tanggalDate = tTanggal.getDate();
        
        if (tanggalDate == null){
    JOptionPane.showMessageDialog(null, "Tanggal Belum Dipilih!");
    return;
    
}
        String tanggalDateString = new SimpleDateFormat("yyyy-MM-dd").format(tanggalDate);
        String jumlah = tJumlahKeluar.getText();
        String keterangan = tKeterangan.getText();
       
        
        String sql = "UPDATE penjualan SET id_produk=?, nama_produk=?, tanggal_penjualan=?, jumlah_keluar=?, keterangan=? WHERE id_penjualan=?";
        try {
            Connection conn = koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kodeProduk);
            ps.setString(2, namaProduk);
            java.sql.Date tanggal = new java.sql.Date(tanggalDate.getTime());
            ps.setDate(3, tanggal);
            ps.setInt(4, Integer.parseInt(jumlah));
            ps.setString(5, keterangan);
            ps.setString(6, idPenjualan);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
        } catch (HeadlessException headlessException) {
        }
        
        loadTabelBarangKeluar();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangKeluarMouseClicked
        // TODO add your handling code here:
             int barisYangDipilih = tblBarangKeluar.rowAtPoint(evt.getPoint());
        
        String idPenjualan = tblBarangKeluar.getValueAt(barisYangDipilih, 0).toString();
        String kodeProduk = tblBarangKeluar.getValueAt(barisYangDipilih, 1).toString();
        String tanggal = tblBarangKeluar.getValueAt(barisYangDipilih, 4).toString();
        String namaProduk = tblBarangKeluar.getValueAt(barisYangDipilih, 2).toString();
        String jumlah  = tblBarangKeluar.getValueAt(barisYangDipilih, 3).toString();
        String keterangan = tblBarangKeluar.getValueAt(barisYangDipilih, 5).toString();
        
        tIdPenjualan.setText(idPenjualan);
        cKodeProduk.setSelectedItem(kodeProduk);
        tIdPenjualan.setEditable(false);
        tNamaProduk.setText(namaProduk);
        
        try {
            java.util.Date date = new SimpleDateFormat("yyy-MM-dd").parse(tanggal);
            tTanggal.setDate(date);
        } catch (ParseException parseException) {
        }
        tJumlahKeluar.setText(jumlah);
        tKeterangan.setText(keterangan);
    }//GEN-LAST:event_tblBarangKeluarMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
          reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
                   String idPenjualan = tIdPenjualan.getText();

        String sql = "DELETE FROM penjualan WHERE id_penjualan=?";
        try {
            Connection conn = koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPenjualan);
            
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        } catch (HeadlessException headlessException) {
        }
        
        loadTabelBarangKeluar();
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cKodeProduk;
    private javax.swing.JLabel jJumlahPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jTotalPenjualan;
    private javax.swing.JTextField tIdPenjualan;
    private javax.swing.JTextField tJumlahKeluar;
    private javax.swing.JTextField tKeterangan;
    private javax.swing.JTextField tNamaProduk;
    private com.toedter.calendar.JDateChooser tTanggal;
    private javax.swing.JTable tblBarangKeluar;
    // End of variables declaration//GEN-END:variables
}
