/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screens.Master.SubMaster;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelLaporan extends javax.swing.JPanel {

    /**
     * Creates new form PanelLaporan
     */
    public PanelLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelAction = new javax.swing.JPanel();
        lblGarisPemisah = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelStatistik = new javax.swing.JPanel();
        panelTotalProduk = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelBottom = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        panelBarangMasuk = new javax.swing.JPanel();
        panelTop1 = new javax.swing.JPanel();
        lblIcon1 = new javax.swing.JLabel();
        panelText1 = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        lblJumlah1 = new javax.swing.JLabel();
        panelCenter1 = new javax.swing.JPanel();
        panelBottom1 = new javax.swing.JPanel();
        lblKeterangan1 = new javax.swing.JLabel();
        panelBarangKeluar = new javax.swing.JPanel();
        panelTop2 = new javax.swing.JPanel();
        lblIcon2 = new javax.swing.JLabel();
        panelText2 = new javax.swing.JPanel();
        lblJudul2 = new javax.swing.JLabel();
        lblJumlah2 = new javax.swing.JLabel();
        panelCenter2 = new javax.swing.JPanel();
        panelBottom2 = new javax.swing.JPanel();
        lblKeterangan2 = new javax.swing.JLabel();
        panelStokMenipis = new javax.swing.JPanel();
        panelTop3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        panelText3 = new javax.swing.JPanel();
        lblJudul3 = new javax.swing.JLabel();
        lblJumlah3 = new javax.swing.JLabel();
        panelCenter3 = new javax.swing.JPanel();
        panelBottom3 = new javax.swing.JPanel();
        lblKeterangan3 = new javax.swing.JLabel();
        panelSupplierOn = new javax.swing.JPanel();
        panelTop4 = new javax.swing.JPanel();
        lblIcon4 = new javax.swing.JLabel();
        panelText4 = new javax.swing.JPanel();
        lblJudul4 = new javax.swing.JLabel();
        lblJumlah4 = new javax.swing.JLabel();
        panelCenter4 = new javax.swing.JPanel();
        panelBottom4 = new javax.swing.JPanel();
        lblKeterangan4 = new javax.swing.JLabel();
        panelSupplierOff = new javax.swing.JPanel();
        panelTop5 = new javax.swing.JPanel();
        lblIcon5 = new javax.swing.JLabel();
        panelText5 = new javax.swing.JPanel();
        lblJudul5 = new javax.swing.JLabel();
        lblJumlah5 = new javax.swing.JLabel();
        panelCenter5 = new javax.swing.JPanel();
        panelBottom5 = new javax.swing.JPanel();
        lblKeterangan5 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDataSupplier = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelUtama.setPreferredSize(new java.awt.Dimension(1000, 650));
        panelUtama.setLayout(new java.awt.BorderLayout());

        panelHeader.setMinimumSize(new java.awt.Dimension(304, 77));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        panelTitle.setBackground(new java.awt.Color(255, 255, 255));
        panelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("Laporan");
        panelTitle.add(lblTitle);

        panelHeader.add(panelTitle);

        panelAction.setBackground(new java.awt.Color(255, 255, 255));
        panelAction.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        lblGarisPemisah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah V2.png"))); // NOI18N
        panelAction.add(lblGarisPemisah);

        lblNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-notification-20.png"))); // NOI18N
        panelAction.add(lblNotification);

        panelHeader.add(panelAction);

        panelUtama.add(panelHeader, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        panelStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        panelStatistik.setPreferredSize(new java.awt.Dimension(760, 120));
        panelStatistik.setLayout(new java.awt.GridLayout(2, 3, 15, 15));

        panelTotalProduk.setBackground(new java.awt.Color(255, 255, 255));
        panelTotalProduk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelTotalProduk.setLayout(new java.awt.BorderLayout());

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-total-produk-47.png"))); // NOI18N
        panelTop.add(lblIcon);

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul.setText("Total Produk");
        panelText.add(lblJudul);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah.setText("0");
        panelText.add(lblJumlah);

        panelTop.add(panelText);

        panelTotalProduk.add(panelTop, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelTotalProduk.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelBottom.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Jumlah Seluruh Item Fisik");
        lblKeterangan.setAlignmentX(0.5F);
        panelBottom.add(lblKeterangan);

        panelTotalProduk.add(panelBottom, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelTotalProduk);

        panelBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        panelBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelBarangMasuk.setLayout(new java.awt.BorderLayout());

        panelTop1.setBackground(new java.awt.Color(255, 255, 255));
        panelTop1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-masuk-47.png"))); // NOI18N
        panelTop1.add(lblIcon1);

        panelText1.setBackground(new java.awt.Color(255, 255, 255));
        panelText1.setLayout(new javax.swing.BoxLayout(panelText1, javax.swing.BoxLayout.Y_AXIS));

        lblJudul1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul1.setText("Barang Masuk");
        panelText1.add(lblJudul1);

        lblJumlah1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah1.setText("0");
        panelText1.add(lblJumlah1);

        panelTop1.add(panelText1);

        panelBarangMasuk.add(panelTop1, java.awt.BorderLayout.NORTH);

        panelCenter1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter1Layout = new javax.swing.GroupLayout(panelCenter1);
        panelCenter1.setLayout(panelCenter1Layout);
        panelCenter1Layout.setHorizontalGroup(
            panelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        panelCenter1Layout.setVerticalGroup(
            panelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBarangMasuk.add(panelCenter1, java.awt.BorderLayout.CENTER);

        panelBottom1.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan1.setText("Total Barang Masuk");
        lblKeterangan1.setAlignmentX(0.5F);
        panelBottom1.add(lblKeterangan1);

        panelBarangMasuk.add(panelBottom1, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelBarangMasuk);

        panelBarangKeluar.setBackground(new java.awt.Color(255, 255, 255));
        panelBarangKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelBarangKeluar.setLayout(new java.awt.BorderLayout());

        panelTop2.setBackground(new java.awt.Color(255, 255, 255));
        panelTop2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-keluar-44.png"))); // NOI18N
        panelTop2.add(lblIcon2);

        panelText2.setBackground(new java.awt.Color(255, 255, 255));
        panelText2.setLayout(new javax.swing.BoxLayout(panelText2, javax.swing.BoxLayout.Y_AXIS));

        lblJudul2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul2.setText("Barang Keluar");
        panelText2.add(lblJudul2);

        lblJumlah2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah2.setText("0");
        panelText2.add(lblJumlah2);

        panelTop2.add(panelText2);

        panelBarangKeluar.add(panelTop2, java.awt.BorderLayout.NORTH);

        panelCenter2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter2Layout = new javax.swing.GroupLayout(panelCenter2);
        panelCenter2.setLayout(panelCenter2Layout);
        panelCenter2Layout.setHorizontalGroup(
            panelCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        panelCenter2Layout.setVerticalGroup(
            panelCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBarangKeluar.add(panelCenter2, java.awt.BorderLayout.CENTER);

        panelBottom2.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan2.setText("Total Barang Keluar");
        lblKeterangan2.setAlignmentX(0.5F);
        panelBottom2.add(lblKeterangan2);

        panelBarangKeluar.add(panelBottom2, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelBarangKeluar);

        panelStokMenipis.setBackground(new java.awt.Color(255, 255, 255));
        panelStokMenipis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelStokMenipis.setLayout(new java.awt.BorderLayout());

        panelTop3.setBackground(new java.awt.Color(255, 255, 255));
        panelTop3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-stok-menipis-44.png"))); // NOI18N
        panelTop3.add(lblIcon3);

        panelText3.setBackground(new java.awt.Color(255, 255, 255));
        panelText3.setLayout(new javax.swing.BoxLayout(panelText3, javax.swing.BoxLayout.Y_AXIS));

        lblJudul3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul3.setText("Stok Menipis");
        panelText3.add(lblJudul3);

        lblJumlah3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah3.setText("0");
        panelText3.add(lblJumlah3);

        panelTop3.add(panelText3);

        panelStokMenipis.add(panelTop3, java.awt.BorderLayout.NORTH);

        panelCenter3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter3Layout = new javax.swing.GroupLayout(panelCenter3);
        panelCenter3.setLayout(panelCenter3Layout);
        panelCenter3Layout.setHorizontalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        panelCenter3Layout.setVerticalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelStokMenipis.add(panelCenter3, java.awt.BorderLayout.CENTER);

        panelBottom3.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan3.setText("Total Produk Hampir");
        lblKeterangan3.setAlignmentX(0.5F);
        panelBottom3.add(lblKeterangan3);

        panelStokMenipis.add(panelBottom3, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelStokMenipis);

        panelSupplierOn.setBackground(new java.awt.Color(255, 255, 255));
        panelSupplierOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelSupplierOn.setLayout(new java.awt.BorderLayout());

        panelTop4.setBackground(new java.awt.Color(255, 255, 255));
        panelTop4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-checkmark-59.png"))); // NOI18N
        panelTop4.add(lblIcon4);

        panelText4.setBackground(new java.awt.Color(255, 255, 255));
        panelText4.setLayout(new javax.swing.BoxLayout(panelText4, javax.swing.BoxLayout.Y_AXIS));

        lblJudul4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul4.setText("Supplier Aktif");
        panelText4.add(lblJudul4);

        lblJumlah4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah4.setText("0");
        panelText4.add(lblJumlah4);

        panelTop4.add(panelText4);

        panelSupplierOn.add(panelTop4, java.awt.BorderLayout.NORTH);

        panelCenter4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter4Layout = new javax.swing.GroupLayout(panelCenter4);
        panelCenter4.setLayout(panelCenter4Layout);
        panelCenter4Layout.setHorizontalGroup(
            panelCenter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenter4Layout.setVerticalGroup(
            panelCenter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelSupplierOn.add(panelCenter4, java.awt.BorderLayout.CENTER);

        panelBottom4.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan4.setText("Total Supplier Aktif");
        lblKeterangan4.setAlignmentX(0.5F);
        panelBottom4.add(lblKeterangan4);

        panelSupplierOn.add(panelBottom4, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelSupplierOn);

        panelSupplierOff.setBackground(new java.awt.Color(255, 255, 255));
        panelSupplierOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelSupplierOff.setLayout(new java.awt.BorderLayout());

        panelTop5.setBackground(new java.awt.Color(255, 255, 255));
        panelTop5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-cancel-59.png"))); // NOI18N
        panelTop5.add(lblIcon5);

        panelText5.setBackground(new java.awt.Color(255, 255, 255));
        panelText5.setLayout(new javax.swing.BoxLayout(panelText5, javax.swing.BoxLayout.Y_AXIS));

        lblJudul5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul5.setText("Supplier Nonaktif");
        panelText5.add(lblJudul5);

        lblJumlah5.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah5.setText("0");
        panelText5.add(lblJumlah5);

        panelTop5.add(panelText5);

        panelSupplierOff.add(panelTop5, java.awt.BorderLayout.NORTH);

        panelCenter5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter5Layout = new javax.swing.GroupLayout(panelCenter5);
        panelCenter5.setLayout(panelCenter5Layout);
        panelCenter5Layout.setHorizontalGroup(
            panelCenter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenter5Layout.setVerticalGroup(
            panelCenter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelSupplierOff.add(panelCenter5, java.awt.BorderLayout.CENTER);

        panelBottom5.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan5.setText("Total Supplier Tidak Aktif");
        lblKeterangan5.setAlignmentX(0.5F);
        panelBottom5.add(lblKeterangan5);

        panelSupplierOff.add(panelBottom5, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelSupplierOff);

        jPanel1.add(panelStatistik, java.awt.BorderLayout.CENTER);

        panelUtama.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(1000, 300));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 75));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 15, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal Awal");
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tanggal Akhir");
        jPanel2.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Laporan");
        jPanel2.add(jLabel3);

        jDateChooser1.setDateFormatString("dd MMMM yyyy");
        jPanel2.add(jDateChooser1);

        jDateChooser2.setDateFormatString("dd MMMM yyyy");
        jPanel2.add(jDateChooser2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Dashboard", "Data Produk", "Data Supplier", "Barang Masuk", "Barang Keluar", " ", " " }));
        jPanel2.add(jComboBox1);

        jPanel18.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jtDataSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Produk", "Nama Produk", "Total Produk", "Total Supplier", "Barang Masuk", "Barang Keluar", "Status"
            }
        ));
        jScrollPane2.setViewportView(jtDataSupplier);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(680, 35));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(200, 88));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Menampilkan 1 -");
        jPanel13.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        jLabel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel13.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel15.setPreferredSize(new java.awt.Dimension(150, 77));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-back-to-20.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel15.add(jButton2);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        jPanel17.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-next-page-20.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel15.add(jButton3);

        jPanel14.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel18.add(jPanel3, java.awt.BorderLayout.CENTER);

        panelUtama.add(jPanel18, java.awt.BorderLayout.PAGE_END);

        add(panelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtDataSupplier;
    private javax.swing.JLabel lblGarisPemisah;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblIcon5;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblJudul3;
    private javax.swing.JLabel lblJudul4;
    private javax.swing.JLabel lblJudul5;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblJumlah1;
    private javax.swing.JLabel lblJumlah2;
    private javax.swing.JLabel lblJumlah3;
    private javax.swing.JLabel lblJumlah4;
    private javax.swing.JLabel lblJumlah5;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblKeterangan1;
    private javax.swing.JLabel lblKeterangan2;
    private javax.swing.JLabel lblKeterangan3;
    private javax.swing.JLabel lblKeterangan4;
    private javax.swing.JLabel lblKeterangan5;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelBarangKeluar;
    private javax.swing.JPanel panelBarangMasuk;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelBottom1;
    private javax.swing.JPanel panelBottom2;
    private javax.swing.JPanel panelBottom3;
    private javax.swing.JPanel panelBottom4;
    private javax.swing.JPanel panelBottom5;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenter1;
    private javax.swing.JPanel panelCenter2;
    private javax.swing.JPanel panelCenter3;
    private javax.swing.JPanel panelCenter4;
    private javax.swing.JPanel panelCenter5;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JPanel panelStokMenipis;
    private javax.swing.JPanel panelSupplierOff;
    private javax.swing.JPanel panelSupplierOn;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelText1;
    private javax.swing.JPanel panelText2;
    private javax.swing.JPanel panelText3;
    private javax.swing.JPanel panelText4;
    private javax.swing.JPanel panelText5;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelTop1;
    private javax.swing.JPanel panelTop2;
    private javax.swing.JPanel panelTop3;
    private javax.swing.JPanel panelTop4;
    private javax.swing.JPanel panelTop5;
    private javax.swing.JPanel panelTotalProduk;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
