/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screens.Master.SubMaster;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelBarangKeluar extends javax.swing.JPanel {

    /**
     * Creates new form PanelBarangKeluar
     */
    public PanelBarangKeluar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelAction = new javax.swing.JPanel();
        lblGarisPemisah = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelStatistik = new javax.swing.JPanel();
        panelSubStatistik = new javax.swing.JPanel();
        panelTotalSupplier = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelBottom = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        panelSupplierOn = new javax.swing.JPanel();
        panelTop3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        panelText3 = new javax.swing.JPanel();
        lblJudul3 = new javax.swing.JLabel();
        lblJumlah3 = new javax.swing.JLabel();
        panelCenter3 = new javax.swing.JPanel();
        panelBottom3 = new javax.swing.JPanel();
        lblKeterangan3 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        panelDataProduk = new javax.swing.JPanel();
        panelHeaderTabel = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        panelTable1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panelNote = new javax.swing.JPanel();
        panelHeaderNotif = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelUtama.setLayout(new java.awt.BorderLayout());

        panelHeader.setMinimumSize(new java.awt.Dimension(304, 77));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        panelTitle.setBackground(new java.awt.Color(255, 255, 255));
        panelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("Barang Keluar");
        panelTitle.add(lblTitle);

        panelHeader.add(panelTitle);

        panelAction.setBackground(new java.awt.Color(255, 255, 255));
        panelAction.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        lblGarisPemisah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah V2.png"))); // NOI18N
        panelAction.add(lblGarisPemisah);

        lblNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-notification-20.png"))); // NOI18N
        panelAction.add(lblNotification);

        panelHeader.add(panelAction);

        panelUtama.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelBody.setLayout(new java.awt.BorderLayout());

        panelStatistik.setPreferredSize(new java.awt.Dimension(100, 150));
        panelStatistik.setLayout(new java.awt.BorderLayout());

        panelSubStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 1, 15));
        panelSubStatistik.setPreferredSize(new java.awt.Dimension(760, 120));
        panelSubStatistik.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        panelTotalSupplier.setBackground(new java.awt.Color(255, 255, 255));
        panelTotalSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelTotalSupplier.setLayout(new java.awt.BorderLayout());

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/Salinan dari Salinan dari Design UI Hijabella Collection_20260714_104825_0000.png"))); // NOI18N
        panelTop.add(lblIcon);

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul.setText("Total Barang Keluar Hari Ini");
        panelText.add(lblJudul);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah.setText("0");
        panelText.add(lblJumlah);

        panelTop.add(panelText);

        panelTotalSupplier.add(panelTop, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        panelTotalSupplier.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelBottom.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Total Unit");
        lblKeterangan.setAlignmentX(0.5F);
        panelBottom.add(lblKeterangan);

        panelTotalSupplier.add(panelBottom, java.awt.BorderLayout.SOUTH);

        panelSubStatistik.add(panelTotalSupplier);

        panelSupplierOn.setBackground(new java.awt.Color(255, 255, 255));
        panelSupplierOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelSupplierOn.setLayout(new java.awt.BorderLayout());

        panelTop3.setBackground(new java.awt.Color(255, 255, 255));
        panelTop3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/Salinan dari Salinan dari Design UI Hijabella Collection_20260714_093023_0000.png"))); // NOI18N
        panelTop3.add(lblIcon3);

        panelText3.setBackground(new java.awt.Color(255, 255, 255));
        panelText3.setLayout(new javax.swing.BoxLayout(panelText3, javax.swing.BoxLayout.Y_AXIS));

        lblJudul3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul3.setText("Total Transaksi Hari Ini");
        panelText3.add(lblJudul3);

        lblJumlah3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah3.setText("0");
        panelText3.add(lblJumlah3);

        panelTop3.add(panelText3);

        panelSupplierOn.add(panelTop3, java.awt.BorderLayout.NORTH);

        panelCenter3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter3Layout = new javax.swing.GroupLayout(panelCenter3);
        panelCenter3.setLayout(panelCenter3Layout);
        panelCenter3Layout.setHorizontalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenter3Layout.setVerticalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        panelSupplierOn.add(panelCenter3, java.awt.BorderLayout.CENTER);

        panelBottom3.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan3.setText("Total Transaksi");
        lblKeterangan3.setAlignmentX(0.5F);
        panelBottom3.add(lblKeterangan3);

        panelSupplierOn.add(panelBottom3, java.awt.BorderLayout.SOUTH);

        panelSubStatistik.add(panelSupplierOn);

        panelStatistik.add(panelSubStatistik, java.awt.BorderLayout.CENTER);

        panelBody.add(panelStatistik, java.awt.BorderLayout.PAGE_START);

        panelContent.setLayout(new java.awt.BorderLayout());

        panelTable.setPreferredSize(new java.awt.Dimension(750, 426));
        panelTable.setLayout(new java.awt.BorderLayout());

        panelDataProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelDataProduk.setLayout(new java.awt.BorderLayout());

        panelHeaderTabel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTitle1.setText("Riwayat Barang Keluar");
        panelHeaderTabel.add(lblTitle1);

        panelDataProduk.add(panelHeaderTabel, java.awt.BorderLayout.PAGE_START);

        panelTable1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Id Produk", "Nama Produk", "Jumlah Keluar", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelTable1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(680, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(200, 88));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Menampilkan 1 -");
        jPanel13.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        jLabel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel13.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel15.setPreferredSize(new java.awt.Dimension(150, 77));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-back-to-20.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel15.add(jButton2);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        jPanel17.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-next-page-20.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel15.add(jButton3);

        jPanel14.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel14, java.awt.BorderLayout.CENTER);

        panelTable1.add(jPanel1, java.awt.BorderLayout.SOUTH);

        panelDataProduk.add(panelTable1, java.awt.BorderLayout.CENTER);

        panelTable.add(panelDataProduk, java.awt.BorderLayout.CENTER);

        panelContent.add(panelTable, java.awt.BorderLayout.LINE_START);

        panelNote.setLayout(new java.awt.BorderLayout());

        panelHeaderNotif.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 15));
        panelHeaderNotif.setPreferredSize(new java.awt.Dimension(240, 40));
        panelHeaderNotif.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Catatan Barang Keluar");
        jLabel2.setIconTextGap(10);
        panelHeaderNotif.add(jLabel2, java.awt.BorderLayout.CENTER);
        panelHeaderNotif.add(jSeparator1, java.awt.BorderLayout.SOUTH);

        panelNote.add(panelHeaderNotif, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel3.setLayout(new java.awt.GridLayout(10, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Id Produk");
        jPanel3.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum ditentukan" }));
        jPanel3.add(jComboBox1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Produk");
        jPanel3.add(jLabel3);
        jPanel3.add(jTextField1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Keluar /Unit");
        jPanel3.add(jLabel4);
        jPanel3.add(jSpinner1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal");
        jPanel3.add(jLabel5);

        jDateChooser1.setDateFormatString("dd MMMM yyyy");
        jPanel3.add(jDateChooser1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Keterangan");
        jPanel3.add(jLabel6);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum ditentukan" }));
        jPanel3.add(jComboBox2);

        panelNote.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 55));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        jButton4.setBackground(new java.awt.Color(96, 60, 17));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Simpan");
        jPanel2.add(jButton4);

        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 60, 17)));
        jPanel2.add(jButton5);

        panelNote.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        panelContent.add(panelNote, java.awt.BorderLayout.CENTER);

        panelBody.add(panelContent, java.awt.BorderLayout.CENTER);

        panelUtama.add(panelBody, java.awt.BorderLayout.CENTER);

        add(panelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblGarisPemisah;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul3;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblJumlah3;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblKeterangan3;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelBottom3;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenter3;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDataProduk;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHeaderNotif;
    private javax.swing.JPanel panelHeaderTabel;
    private javax.swing.JPanel panelNote;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JPanel panelSubStatistik;
    private javax.swing.JPanel panelSupplierOn;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTable1;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelText3;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelTop3;
    private javax.swing.JPanel panelTotalSupplier;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
