/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screens.Master.SubMaster;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelSetting extends javax.swing.JPanel {

    /**
     * Creates new form PanelSetting
     */
    public PanelSetting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelUtama.setPreferredSize(new java.awt.Dimension(1000, 650));
        panelUtama.setLayout(new java.awt.BorderLayout());

        panelHeader.setMinimumSize(new java.awt.Dimension(304, 77));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        panelTitle.setBackground(new java.awt.Color(250, 245, 241));
        panelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("Pengaturan Akun");
        panelTitle.add(lblTitle);

        panelHeader.add(panelTitle);

        panelUtama.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelContent.setBackground(new java.awt.Color(250, 245, 241));
        panelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 55, 35, 55));
        panelContent.setLayout(new java.awt.GridLayout(6, 0, 0, 25));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(250, 245, 241));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/Salinan dari Salinan dari Design UI Hijabella Collection_20260714_135246_0000.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel8.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jTextField1.setBackground(new java.awt.Color(250, 245, 241));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(null);
        jPanel8.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(250, 245, 241));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-customer-30.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jPanel9.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jTextField2.setBackground(new java.awt.Color(250, 245, 241));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        jPanel9.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(250, 245, 241));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jTextField3.setBackground(new java.awt.Color(250, 245, 241));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setBorder(null);
        jPanel10.add(jTextField3, java.awt.BorderLayout.CENTER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-customer-30.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jPanel10.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(250, 245, 241));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-email-30.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jPanel11.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jTextField4.setBackground(new java.awt.Color(250, 245, 241));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setBorder(null);
        jPanel11.add(jTextField4, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/click 20px.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jButton2.setContentAreaFilled(false);
        jPanel11.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel11, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(250, 245, 241));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-whatsapp-30.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jPanel12.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jTextField5.setBackground(new java.awt.Color(250, 245, 241));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setBorder(null);
        jPanel12.add(jTextField5, java.awt.BorderLayout.CENTER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/click 20px.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jButton5.setContentAreaFilled(false);
        jPanel12.add(jButton5, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel12, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 135)));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(250, 245, 241));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-password-30.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jPanel13.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jTextField6.setBackground(new java.awt.Color(250, 245, 241));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setBorder(null);
        jPanel13.add(jTextField6, java.awt.BorderLayout.CENTER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/click 20px.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jButton6.setContentAreaFilled(false);
        jPanel13.add(jButton6, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanel13, java.awt.BorderLayout.CENTER);

        panelContent.add(jPanel7);

        panelUtama.add(panelContent, java.awt.BorderLayout.CENTER);

        add(panelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
