/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screens.Master.SubMaster;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelDataSupplier extends javax.swing.JPanel {

    /**
     * Creates new form PanelDataSupplier
     */
    public PanelDataSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelAction = new javax.swing.JPanel();
        lblGarisPemisah = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        panelStatnButton = new javax.swing.JPanel();
        panelStatistik = new javax.swing.JPanel();
        panelSubStatistik = new javax.swing.JPanel();
        panelTotalSupplier = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelBottom = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        panelSupplierOn = new javax.swing.JPanel();
        panelTop3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        panelText3 = new javax.swing.JPanel();
        lblJudul3 = new javax.swing.JLabel();
        lblJumlah3 = new javax.swing.JLabel();
        panelCenter3 = new javax.swing.JPanel();
        panelBottom3 = new javax.swing.JPanel();
        lblKeterangan3 = new javax.swing.JLabel();
        panelSupplierOff = new javax.swing.JPanel();
        panelTop4 = new javax.swing.JPanel();
        lblIcon4 = new javax.swing.JLabel();
        panelText4 = new javax.swing.JPanel();
        lblJudul4 = new javax.swing.JLabel();
        lblJumlah4 = new javax.swing.JLabel();
        panelCenter4 = new javax.swing.JPanel();
        panelBottom4 = new javax.swing.JPanel();
        lblKeterangan4 = new javax.swing.JLabel();
        panelTengah = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        panelInputKiri = new javax.swing.JPanel();
        lblIdSupplier = new javax.swing.JLabel();
        tIdSupplier = new javax.swing.JTextField();
        lblNamaSupplier = new javax.swing.JLabel();
        tNamaSupplier = new javax.swing.JTextField();
        panelInputKanan = new javax.swing.JPanel();
        lblNoTelp = new javax.swing.JLabel();
        tNoTelp = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        tKota = new javax.swing.JTextField();
        panelButton = new javax.swing.JPanel();
        panelIsiButton = new javax.swing.JPanel();
        panelCari = new javax.swing.JPanel();
        lblIconCari = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panelCbnTable = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        panelCb = new javax.swing.JPanel();
        panelSubCb = new javax.swing.JPanel();
        cbKota = new javax.swing.JComboBox<>();
        panelTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDataSupplier = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelUtama.setPreferredSize(new java.awt.Dimension(1000, 650));
        panelUtama.setLayout(new java.awt.BorderLayout());

        panelHeader.setMinimumSize(new java.awt.Dimension(304, 77));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        panelTitle.setBackground(new java.awt.Color(255, 255, 255));
        panelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("Data Supplier");
        panelTitle.add(lblTitle);

        panelHeader.add(panelTitle);

        panelAction.setBackground(new java.awt.Color(255, 255, 255));
        panelAction.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        lblGarisPemisah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah V2.png"))); // NOI18N
        panelAction.add(lblGarisPemisah);

        lblNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-notification-20.png"))); // NOI18N
        panelAction.add(lblNotification);

        panelHeader.add(panelAction);

        panelUtama.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelStatnButton.setLayout(new java.awt.BorderLayout());

        panelStatistik.setPreferredSize(new java.awt.Dimension(100, 150));
        panelStatistik.setLayout(new java.awt.BorderLayout());

        panelSubStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 1, 15));
        panelSubStatistik.setPreferredSize(new java.awt.Dimension(760, 120));
        panelSubStatistik.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        panelTotalSupplier.setBackground(new java.awt.Color(255, 255, 255));
        panelTotalSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelTotalSupplier.setLayout(new java.awt.BorderLayout());

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/Salinan dari Salinan dari Design UI Hijabella Collection_20260714_064552_0000.png"))); // NOI18N
        panelTop.add(lblIcon);

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul.setText("Total Supplier");
        panelText.add(lblJudul);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah.setText("0");
        panelText.add(lblJumlah);

        panelTop.add(panelText);

        panelTotalSupplier.add(panelTop, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        panelTotalSupplier.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelBottom.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Jumlah Seluruh Supplier");
        lblKeterangan.setAlignmentX(0.5F);
        panelBottom.add(lblKeterangan);

        panelTotalSupplier.add(panelBottom, java.awt.BorderLayout.SOUTH);

        panelSubStatistik.add(panelTotalSupplier);

        panelSupplierOn.setBackground(new java.awt.Color(255, 255, 255));
        panelSupplierOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelSupplierOn.setLayout(new java.awt.BorderLayout());

        panelTop3.setBackground(new java.awt.Color(255, 255, 255));
        panelTop3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-checkmark-59.png"))); // NOI18N
        panelTop3.add(lblIcon3);

        panelText3.setBackground(new java.awt.Color(255, 255, 255));
        panelText3.setLayout(new javax.swing.BoxLayout(panelText3, javax.swing.BoxLayout.Y_AXIS));

        lblJudul3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul3.setText("Supplier Aktif");
        panelText3.add(lblJudul3);

        lblJumlah3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah3.setText("0");
        panelText3.add(lblJumlah3);

        panelTop3.add(panelText3);

        panelSupplierOn.add(panelTop3, java.awt.BorderLayout.NORTH);

        panelCenter3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter3Layout = new javax.swing.GroupLayout(panelCenter3);
        panelCenter3.setLayout(panelCenter3Layout);
        panelCenter3Layout.setHorizontalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenter3Layout.setVerticalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        panelSupplierOn.add(panelCenter3, java.awt.BorderLayout.CENTER);

        panelBottom3.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan3.setText("Total Supplier Aktif");
        lblKeterangan3.setAlignmentX(0.5F);
        panelBottom3.add(lblKeterangan3);

        panelSupplierOn.add(panelBottom3, java.awt.BorderLayout.SOUTH);

        panelSubStatistik.add(panelSupplierOn);

        panelSupplierOff.setBackground(new java.awt.Color(255, 255, 255));
        panelSupplierOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelSupplierOff.setLayout(new java.awt.BorderLayout());

        panelTop4.setBackground(new java.awt.Color(255, 255, 255));
        panelTop4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-cancel-59.png"))); // NOI18N
        panelTop4.add(lblIcon4);

        panelText4.setBackground(new java.awt.Color(255, 255, 255));
        panelText4.setLayout(new javax.swing.BoxLayout(panelText4, javax.swing.BoxLayout.Y_AXIS));

        lblJudul4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul4.setText("Supplier Nonaktif");
        panelText4.add(lblJudul4);

        lblJumlah4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah4.setText("0");
        panelText4.add(lblJumlah4);

        panelTop4.add(panelText4);

        panelSupplierOff.add(panelTop4, java.awt.BorderLayout.NORTH);

        panelCenter4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter4Layout = new javax.swing.GroupLayout(panelCenter4);
        panelCenter4.setLayout(panelCenter4Layout);
        panelCenter4Layout.setHorizontalGroup(
            panelCenter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCenter4Layout.setVerticalGroup(
            panelCenter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        panelSupplierOff.add(panelCenter4, java.awt.BorderLayout.CENTER);

        panelBottom4.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan4.setText("Total Supplier Tidak Aktif");
        lblKeterangan4.setAlignmentX(0.5F);
        panelBottom4.add(lblKeterangan4);

        panelSupplierOff.add(panelBottom4, java.awt.BorderLayout.SOUTH);

        panelSubStatistik.add(panelSupplierOff);

        panelStatistik.add(panelSubStatistik, java.awt.BorderLayout.CENTER);

        panelStatnButton.add(panelStatistik, java.awt.BorderLayout.PAGE_START);

        panelTengah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 10, 1));
        panelTengah.setLayout(new java.awt.BorderLayout());

        panelInput.setPreferredSize(new java.awt.Dimension(100, 75));
        panelInput.setLayout(new java.awt.BorderLayout());

        panelInputKiri.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        panelInputKiri.setPreferredSize(new java.awt.Dimension(500, 100));
        panelInputKiri.setLayout(new java.awt.GridLayout(2, 2, 0, 5));

        lblIdSupplier.setText("Id Supplier");
        panelInputKiri.add(lblIdSupplier);
        panelInputKiri.add(tIdSupplier);

        lblNamaSupplier.setText("Nama Supplier");
        panelInputKiri.add(lblNamaSupplier);
        panelInputKiri.add(tNamaSupplier);

        panelInput.add(panelInputKiri, java.awt.BorderLayout.WEST);

        panelInputKanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelInputKanan.setLayout(new java.awt.GridLayout(2, 2, 0, 5));

        lblNoTelp.setText("No. Telp");
        panelInputKanan.add(lblNoTelp);
        panelInputKanan.add(tNoTelp);

        lblKota.setText("Kota/Kabupaten");
        panelInputKanan.add(lblKota);
        panelInputKanan.add(tKota);

        panelInput.add(panelInputKanan, java.awt.BorderLayout.CENTER);

        panelTengah.add(panelInput, java.awt.BorderLayout.PAGE_START);

        panelButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        panelButton.setLayout(new java.awt.BorderLayout());

        panelIsiButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        panelIsiButton.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        panelCari.setBackground(new java.awt.Color(255, 255, 255));
        panelCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelCari.setLayout(new java.awt.BorderLayout());

        lblIconCari.setBackground(new java.awt.Color(255, 255, 255));
        lblIconCari.setForeground(new java.awt.Color(255, 255, 255));
        lblIconCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/Salinan dari Salinan dari Design UI Hijabella Collection_20260709_142437_0000.png"))); // NOI18N
        lblIconCari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        panelCari.add(lblIconCari, java.awt.BorderLayout.WEST);

        tCari.setBorder(null);
        panelCari.add(tCari, java.awt.BorderLayout.CENTER);

        panelIsiButton.add(panelCari);

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        panelIsiButton.add(btnTambah);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        panelIsiButton.add(btnUbah);

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        panelIsiButton.add(btnHapus);

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        panelIsiButton.add(btnReset);

        panelButton.add(panelIsiButton, java.awt.BorderLayout.CENTER);

        panelTengah.add(panelButton, java.awt.BorderLayout.CENTER);

        panelStatnButton.add(panelTengah, java.awt.BorderLayout.CENTER);

        panelUtama.add(panelStatnButton, java.awt.BorderLayout.CENTER);

        panelCbnTable.setPreferredSize(new java.awt.Dimension(1000, 300));
        panelCbnTable.setLayout(new java.awt.BorderLayout());

        panelBody.setPreferredSize(new java.awt.Dimension(1000, 350));
        panelBody.setLayout(new javax.swing.BoxLayout(panelBody, javax.swing.BoxLayout.Y_AXIS));

        panelTable.setLayout(new java.awt.BorderLayout());

        panelCb.setPreferredSize(new java.awt.Dimension(1000, 100));
        panelCb.setLayout(new java.awt.BorderLayout());

        panelSubCb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        panelSubCb.setPreferredSize(new java.awt.Dimension(1000, 150));
        panelSubCb.setLayout(new java.awt.GridLayout(1, 0));

        cbKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Berdasarkan Kota", "Jombang", "Kediri", "Nganjuk" }));
        panelSubCb.add(cbKota);

        panelCb.add(panelSubCb, java.awt.BorderLayout.NORTH);

        panelTable.add(panelCb, java.awt.BorderLayout.NORTH);

        panelTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelTabel.setLayout(new java.awt.BorderLayout());

        jtDataSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Id Supplier", "Nama Supplier", "No. Telp", "Kota/Kabupaten"
            }
        ));
        jScrollPane2.setViewportView(jtDataSupplier);

        panelTabel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(680, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(200, 88));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Menampilkan 1 -");
        jPanel13.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        jLabel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel13.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel15.setPreferredSize(new java.awt.Dimension(150, 77));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-back-to-20.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel15.add(jButton2);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        jPanel17.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-next-page-20.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel15.add(jButton3);

        jPanel14.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel14, java.awt.BorderLayout.CENTER);

        panelTabel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        panelTable.add(panelTabel, java.awt.BorderLayout.CENTER);

        panelBody.add(panelTable);

        panelCbnTable.add(panelBody, java.awt.BorderLayout.SOUTH);

        panelUtama.add(panelCbnTable, java.awt.BorderLayout.SOUTH);

        add(panelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbKota;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtDataSupplier;
    private javax.swing.JLabel lblGarisPemisah;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblIconCari;
    private javax.swing.JLabel lblIdSupplier;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul3;
    private javax.swing.JLabel lblJudul4;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblJumlah3;
    private javax.swing.JLabel lblJumlah4;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblKeterangan3;
    private javax.swing.JLabel lblKeterangan4;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblNamaSupplier;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelBottom3;
    private javax.swing.JPanel panelBottom4;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelCb;
    private javax.swing.JPanel panelCbnTable;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenter3;
    private javax.swing.JPanel panelCenter4;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelInputKanan;
    private javax.swing.JPanel panelInputKiri;
    private javax.swing.JPanel panelIsiButton;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JPanel panelStatnButton;
    private javax.swing.JPanel panelSubCb;
    private javax.swing.JPanel panelSubStatistik;
    private javax.swing.JPanel panelSupplierOff;
    private javax.swing.JPanel panelSupplierOn;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTengah;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelText3;
    private javax.swing.JPanel panelText4;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelTop3;
    private javax.swing.JPanel panelTop4;
    private javax.swing.JPanel panelTotalSupplier;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIdSupplier;
    private javax.swing.JTextField tKota;
    private javax.swing.JTextField tNamaSupplier;
    private javax.swing.JTextField tNoTelp;
    // End of variables declaration//GEN-END:variables
}
