/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screens.Master.SubMaster;

import Screens.Master.FrameMaster;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    private FrameMaster frame;

    public PanelDashboard() {
        initComponents();
        this.frame = frame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelAction = new javax.swing.JPanel();
        lblGarisPemisah = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        panelStatistik = new javax.swing.JPanel();
        panelTotalProduk = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelBottom = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        panelBarangMasuk = new javax.swing.JPanel();
        panelTop1 = new javax.swing.JPanel();
        lblIcon1 = new javax.swing.JLabel();
        panelText1 = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        lblJumlah1 = new javax.swing.JLabel();
        panelCenter1 = new javax.swing.JPanel();
        panelBottom1 = new javax.swing.JPanel();
        lblKeterangan1 = new javax.swing.JLabel();
        panelBarangKeluar = new javax.swing.JPanel();
        panelTop2 = new javax.swing.JPanel();
        lblIcon2 = new javax.swing.JLabel();
        panelText2 = new javax.swing.JPanel();
        lblJudul2 = new javax.swing.JLabel();
        lblJumlah2 = new javax.swing.JLabel();
        panelCenter2 = new javax.swing.JPanel();
        panelBottom2 = new javax.swing.JPanel();
        lblKeterangan2 = new javax.swing.JLabel();
        panelStokMenipis = new javax.swing.JPanel();
        panelTop3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        panelText3 = new javax.swing.JPanel();
        lblJudul3 = new javax.swing.JLabel();
        lblJumlah3 = new javax.swing.JLabel();
        panelCenter3 = new javax.swing.JPanel();
        panelBottom3 = new javax.swing.JPanel();
        lblKeterangan3 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelDataProduk = new javax.swing.JPanel();
        panelHeaderTabel = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panelNotifikasi = new javax.swing.JPanel();
        panelHeaderNotif = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelIsiNotif = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelFooterNotif = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelUtama.setPreferredSize(new java.awt.Dimension(1000, 650));
        panelUtama.setLayout(new javax.swing.BoxLayout(panelUtama, javax.swing.BoxLayout.Y_AXIS));

        panelHeader.setMinimumSize(new java.awt.Dimension(304, 77));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));

        panelTitle.setBackground(new java.awt.Color(255, 255, 255));
        panelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("Dashboard");
        panelTitle.add(lblTitle);

        panelHeader.add(panelTitle);

        panelAction.setBackground(new java.awt.Color(255, 255, 255));
        panelAction.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        lblGarisPemisah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Komponen/Garis Pemisah V2.png"))); // NOI18N
        panelAction.add(lblGarisPemisah);

        lblNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-notification-20.png"))); // NOI18N
        panelAction.add(lblNotification);

        panelHeader.add(panelAction);

        panelUtama.add(panelHeader);

        panelStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 1, 15));
        panelStatistik.setPreferredSize(new java.awt.Dimension(760, 120));
        panelStatistik.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        panelTotalProduk.setBackground(new java.awt.Color(255, 255, 255));
        panelTotalProduk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelTotalProduk.setLayout(new java.awt.BorderLayout());

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-total-produk-47.png"))); // NOI18N
        panelTop.add(lblIcon);

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul.setText("Total Produk");
        panelText.add(lblJudul);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah.setText("0");
        panelText.add(lblJumlah);

        panelTop.add(panelText);

        panelTotalProduk.add(panelTop, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelTotalProduk.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelBottom.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Jumlah Seluruh Item Fisik");
        lblKeterangan.setAlignmentX(0.5F);
        panelBottom.add(lblKeterangan);

        panelTotalProduk.add(panelBottom, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelTotalProduk);

        panelBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        panelBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelBarangMasuk.setLayout(new java.awt.BorderLayout());

        panelTop1.setBackground(new java.awt.Color(255, 255, 255));
        panelTop1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-masuk-47.png"))); // NOI18N
        panelTop1.add(lblIcon1);

        panelText1.setBackground(new java.awt.Color(255, 255, 255));
        panelText1.setLayout(new javax.swing.BoxLayout(panelText1, javax.swing.BoxLayout.Y_AXIS));

        lblJudul1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul1.setText("Barang Masuk");
        panelText1.add(lblJudul1);

        lblJumlah1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah1.setText("0");
        panelText1.add(lblJumlah1);

        panelTop1.add(panelText1);

        panelBarangMasuk.add(panelTop1, java.awt.BorderLayout.NORTH);

        panelCenter1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter1Layout = new javax.swing.GroupLayout(panelCenter1);
        panelCenter1.setLayout(panelCenter1Layout);
        panelCenter1Layout.setHorizontalGroup(
            panelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelCenter1Layout.setVerticalGroup(
            panelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBarangMasuk.add(panelCenter1, java.awt.BorderLayout.CENTER);

        panelBottom1.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan1.setText("Total Barang Masuk Hari Ini");
        lblKeterangan1.setAlignmentX(0.5F);
        panelBottom1.add(lblKeterangan1);

        panelBarangMasuk.add(panelBottom1, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelBarangMasuk);

        panelBarangKeluar.setBackground(new java.awt.Color(255, 255, 255));
        panelBarangKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelBarangKeluar.setLayout(new java.awt.BorderLayout());

        panelTop2.setBackground(new java.awt.Color(255, 255, 255));
        panelTop2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-keluar-44.png"))); // NOI18N
        panelTop2.add(lblIcon2);

        panelText2.setBackground(new java.awt.Color(255, 255, 255));
        panelText2.setLayout(new javax.swing.BoxLayout(panelText2, javax.swing.BoxLayout.Y_AXIS));

        lblJudul2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul2.setText("Barang Keluar");
        panelText2.add(lblJudul2);

        lblJumlah2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah2.setText("0");
        panelText2.add(lblJumlah2);

        panelTop2.add(panelText2);

        panelBarangKeluar.add(panelTop2, java.awt.BorderLayout.NORTH);

        panelCenter2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter2Layout = new javax.swing.GroupLayout(panelCenter2);
        panelCenter2.setLayout(panelCenter2Layout);
        panelCenter2Layout.setHorizontalGroup(
            panelCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelCenter2Layout.setVerticalGroup(
            panelCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBarangKeluar.add(panelCenter2, java.awt.BorderLayout.CENTER);

        panelBottom2.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        panelBottom2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan2.setText("Total Barang Keluar Hari Ini");
        lblKeterangan2.setAlignmentX(0.5F);
        panelBottom2.add(lblKeterangan2);

        panelBarangKeluar.add(panelBottom2, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelBarangKeluar);

        panelStokMenipis.setBackground(new java.awt.Color(255, 255, 255));
        panelStokMenipis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 215, 199)));
        panelStokMenipis.setLayout(new java.awt.BorderLayout());

        panelTop3.setBackground(new java.awt.Color(255, 255, 255));
        panelTop3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-stok-menipis-44.png"))); // NOI18N
        panelTop3.add(lblIcon3);

        panelText3.setBackground(new java.awt.Color(255, 255, 255));
        panelText3.setLayout(new javax.swing.BoxLayout(panelText3, javax.swing.BoxLayout.Y_AXIS));

        lblJudul3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul3.setText("Stok Menipis");
        panelText3.add(lblJudul3);

        lblJumlah3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblJumlah3.setText("0");
        panelText3.add(lblJumlah3);

        panelTop3.add(panelText3);

        panelStokMenipis.add(panelTop3, java.awt.BorderLayout.NORTH);

        panelCenter3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCenter3Layout = new javax.swing.GroupLayout(panelCenter3);
        panelCenter3.setLayout(panelCenter3Layout);
        panelCenter3Layout.setHorizontalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelCenter3Layout.setVerticalGroup(
            panelCenter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelStokMenipis.add(panelCenter3, java.awt.BorderLayout.CENTER);

        panelBottom3.setBackground(new java.awt.Color(255, 255, 255));
        panelBottom3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblKeterangan3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblKeterangan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan3.setText("Total Produk Hampir Habis");
        lblKeterangan3.setAlignmentX(0.5F);
        panelBottom3.add(lblKeterangan3);

        panelStokMenipis.add(panelBottom3, java.awt.BorderLayout.SOUTH);

        panelStatistik.add(panelStokMenipis);

        panelUtama.add(panelStatistik);

        panelBody.setPreferredSize(new java.awt.Dimension(760, 330));
        panelBody.setLayout(new java.awt.BorderLayout());

        panelDataProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelDataProduk.setLayout(new java.awt.BorderLayout());

        panelHeaderTabel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTitle1.setText("Keterangan Data Produk");
        panelHeaderTabel.add(lblTitle1);

        panelDataProduk.add(panelHeaderTabel, java.awt.BorderLayout.PAGE_START);

        panelTable.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Produk", "Nama Produk", "Stok", "Harga", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(680, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(200, 88));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Menampilkan 1 -");
        jPanel13.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        jLabel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel13.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel15.setPreferredSize(new java.awt.Dimension(150, 77));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-back-to-20.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel15.add(jButton2);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        jPanel17.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-next-page-20.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel15.add(jButton3);

        jPanel14.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel14, java.awt.BorderLayout.CENTER);

        panelTable.add(jPanel1, java.awt.BorderLayout.SOUTH);

        panelDataProduk.add(panelTable, java.awt.BorderLayout.CENTER);

        panelBody.add(panelDataProduk, java.awt.BorderLayout.CENTER);

        panelNotifikasi.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 10));
        panelNotifikasi.setPreferredSize(new java.awt.Dimension(300, 330));
        panelNotifikasi.setLayout(new java.awt.BorderLayout());

        panelHeaderNotif.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 1));
        panelHeaderNotif.setPreferredSize(new java.awt.Dimension(240, 40));
        panelHeaderNotif.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-notifikasi-22.png"))); // NOI18N
        jLabel2.setText("Notifikasi");
        jLabel2.setIconTextGap(10);
        panelHeaderNotif.add(jLabel2, java.awt.BorderLayout.CENTER);

        panelNotifikasi.add(panelHeaderNotif, java.awt.BorderLayout.PAGE_START);

        panelIsiNotif.setLayout(new javax.swing.BoxLayout(panelIsiNotif, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 72));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-perintah-21.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("1 menit ago");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel5.add(jLabel5, java.awt.BorderLayout.EAST);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel9.add(jLabel15, java.awt.BorderLayout.WEST);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Produk Hampir Habis");
        jPanel12.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel7.setText("Nama Produk");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 1, 1, 1));
        jPanel12.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        panelIsiNotif.add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 72));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-masuk-22.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("1 jam ago");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel6.add(jLabel9, java.awt.BorderLayout.EAST);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Nama Produk (0)");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 1, 1, 1));
        jPanel10.add(jLabel10, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Barang Masuk Baru");
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel10.add(jLabel11, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        panelIsiNotif.add(jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(240, 72));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/icons8-barang-keluar-22.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel3.add(jLabel4, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("1 jam ago");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel7.add(jLabel12, java.awt.BorderLayout.EAST);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("Nama Produk (0)");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 1, 1, 1));
        jPanel11.add(jLabel13, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Barang Keluar Baru");
        jPanel11.add(jLabel14, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        panelIsiNotif.add(jPanel3);

        panelNotifikasi.add(panelIsiNotif, java.awt.BorderLayout.CENTER);

        jSeparator1.setForeground(new java.awt.Color(229, 208, 185));

        jButton1.setForeground(new java.awt.Color(102, 28, 28));
        jButton1.setText("Lihat Semua");

        javax.swing.GroupLayout panelFooterNotifLayout = new javax.swing.GroupLayout(panelFooterNotif);
        panelFooterNotif.setLayout(panelFooterNotifLayout);
        panelFooterNotifLayout.setHorizontalGroup(
            panelFooterNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterNotifLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterNotifLayout.createSequentialGroup()
                        .addGap(0, 175, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panelFooterNotifLayout.setVerticalGroup(
            panelFooterNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterNotifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        panelNotifikasi.add(panelFooterNotif, java.awt.BorderLayout.PAGE_END);

        panelBody.add(panelNotifikasi, java.awt.BorderLayout.EAST);

        panelUtama.add(panelBody);

        add(panelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGarisPemisah;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblJudul3;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblJumlah1;
    private javax.swing.JLabel lblJumlah2;
    private javax.swing.JLabel lblJumlah3;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblKeterangan1;
    private javax.swing.JLabel lblKeterangan2;
    private javax.swing.JLabel lblKeterangan3;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelBarangKeluar;
    private javax.swing.JPanel panelBarangMasuk;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelBottom1;
    private javax.swing.JPanel panelBottom2;
    private javax.swing.JPanel panelBottom3;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenter1;
    private javax.swing.JPanel panelCenter2;
    private javax.swing.JPanel panelCenter3;
    private javax.swing.JPanel panelDataProduk;
    private javax.swing.JPanel panelFooterNotif;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHeaderNotif;
    private javax.swing.JPanel panelHeaderTabel;
    private javax.swing.JPanel panelIsiNotif;
    private javax.swing.JPanel panelNotifikasi;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JPanel panelStokMenipis;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelText1;
    private javax.swing.JPanel panelText2;
    private javax.swing.JPanel panelText3;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelTop1;
    private javax.swing.JPanel panelTop2;
    private javax.swing.JPanel panelTop3;
    private javax.swing.JPanel panelTotalProduk;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
