/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginAplikasi;

import bahan1.AppTheme;
import bahanLogin.PanelLogin;
import bahanLogin.PanelRegister;
import bahanLogin.PanelForgotPassword;



/**
 *
 * @author achmad_khusnul_yakin
 */
public class FrameLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLogin.class.getName());

    /**
     * Creates new form FrameAuth
     */
    public FrameLogin() {
        initComponents();
        AppTheme.applyThemeAuth();

        panelContent.add(new PanelLogin(this), "LOGIN");
        panelContent.add(new PanelRegister(this), "REGISTER");
        panelContent.add(new PanelForgotPassword(this), "FORGOT");
        showPanel("LOGIN");
        panelUtama.remove(panelBackground);
        panelBackground = new bahan1.AppBackgroundPanel();
        panelBackground.setPreferredSize(new java.awt.Dimension(420, 533));
        panelUtama.add(panelBackground, java.awt.BorderLayout.WEST);
        panelUtama.revalidate();
        panelUtama.repaint();
    }

    public void showPanel(String namaPanel) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelContent.getLayout();
        card.show(panelContent, namaPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelBackground = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Autentikasi");

        panelUtama.setLayout(new java.awt.BorderLayout());

        panelBackground.setBackground(new java.awt.Color(253, 247, 242));
        panelBackground.setPreferredSize(new java.awt.Dimension(420, 533));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        panelUtama.add(panelBackground, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(253, 247, 242));
        panelContent.setPreferredSize(new java.awt.Dimension(580, 533));
        panelContent.setLayout(new java.awt.CardLayout());
        panelUtama.add(panelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBackground;
    public static javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
