/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FiturAplikasi;
import LoginAplikasi.FrameLogin;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Eka Melawan ERROR & auliaasmarani
 */
public class FrameDashbord extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameDashbord.class.getName());
private CardLayout cardLayout;
    /**
     * Creates new form framebarangKeluar
     */
    public FrameDashbord() throws SQLException {
        initComponents();
        inisiasiPanel();
    }
    void inisiasiPanel() throws SQLException{
        cardLayout = cardLayout = (CardLayout)panelContent.getLayout();
        panelContent.add(new PanelDashboard(), "dashboard");
        panelContent.add(new panelAbout2(), "about");
        panelContent.add(new PanelBarangMasuk(), "barangMasuk");
        panelContent.add(new PanelBarangKeluar(), "barangKeluar");
        panelContent.add(new PanelDataProduk(), "dataProduk");
        panelContent.add(new PanelDataSupplier(), "dataSupplier");
        panelContent.add(new PanelLaporan(), "laporan");
        panelContent.add(new pengaturanAkun(), "pengaturanAkun");
       
        
      
        
        panelContent.revalidate();
        panelContent.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidbar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDataProduk = new javax.swing.JButton();
        btnDataSupplier = new javax.swing.JButton();
        btnBarangMasuk = new javax.swing.JButton();
        btnBarangKeluar = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));
        setPreferredSize(new java.awt.Dimension(2000, 3000));

        panelSidbar.setBackground(new java.awt.Color(96, 60, 17));
        panelSidbar.setPreferredSize(new java.awt.Dimension(300, 400));

        btnDashboard.setBackground(new java.awt.Color(96, 60, 17));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(201, 160, 160));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-home-25.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDashboard.setIconTextGap(5);
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/logo baru (2).png"))); // NOI18N

        btnDataProduk.setBackground(new java.awt.Color(96, 60, 17));
        btnDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDataProduk.setForeground(new java.awt.Color(201, 160, 160));
        btnDataProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-analyze-20.png"))); // NOI18N
        btnDataProduk.setText("Data Produk");
        btnDataProduk.setBorderPainted(false);
        btnDataProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDataProduk.setIconTextGap(10);
        btnDataProduk.addActionListener(this::btnDataProdukActionPerformed);

        btnDataSupplier.setBackground(new java.awt.Color(96, 60, 17));
        btnDataSupplier.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDataSupplier.setForeground(new java.awt.Color(201, 160, 160));
        btnDataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-warehouse-20.png"))); // NOI18N
        btnDataSupplier.setText("Data Supplier");
        btnDataSupplier.setBorderPainted(false);
        btnDataSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDataSupplier.setIconTextGap(10);
        btnDataSupplier.addActionListener(this::btnDataSupplierActionPerformed);

        btnBarangMasuk.setBackground(new java.awt.Color(96, 60, 17));
        btnBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBarangMasuk.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-delivery-box-20.png"))); // NOI18N
        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.setBorderPainted(false);
        btnBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBarangMasuk.setIconTextGap(10);
        btnBarangMasuk.addActionListener(this::btnBarangMasukActionPerformed);

        btnBarangKeluar.setBackground(new java.awt.Color(96, 60, 17));
        btnBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBarangKeluar.setForeground(new java.awt.Color(201, 160, 160));
        btnBarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-return-20.png"))); // NOI18N
        btnBarangKeluar.setText("Barang Keluar");
        btnBarangKeluar.setBorderPainted(false);
        btnBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBarangKeluar.setIconTextGap(10);
        btnBarangKeluar.addActionListener(this::btnBarangKeluarActionPerformed);

        btnLaporan.setBackground(new java.awt.Color(96, 60, 17));
        btnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(201, 160, 160));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-report-20.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorderPainted(false);
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLaporan.setIconTextGap(10);
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        btnSetting.setBackground(new java.awt.Color(96, 60, 17));
        btnSetting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(201, 160, 160));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-setting-20.png"))); // NOI18N
        btnSetting.setText("Setting");
        btnSetting.setBorderPainted(false);
        btnSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSetting.setIconTextGap(10);
        btnSetting.addActionListener(this::btnSettingActionPerformed);

        btnAbout.setBackground(new java.awt.Color(96, 60, 17));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(201, 160, 160));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-about-20 (1).png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorderPainted(false);
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAbout.setIconTextGap(10);
        btnAbout.addActionListener(this::btnAboutActionPerformed);

        jButton9.setBackground(new java.awt.Color(96, 60, 17));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton9.setForeground(new java.awt.Color(201, 160, 160));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FiturAplikasi/img/icons8-logout-20.png"))); // NOI18N
        jButton9.setText("Logout");
        jButton9.setBorderPainted(false);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton9.setIconTextGap(10);
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jSeparator1.setForeground(new java.awt.Color(201, 160, 160));

        javax.swing.GroupLayout panelSidbarLayout = new javax.swing.GroupLayout(panelSidbar);
        panelSidbar.setLayout(panelSidbarLayout);
        panelSidbarLayout.setHorizontalGroup(
            panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidbarLayout.createSequentialGroup()
                .addGroup(panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBarangKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSidbarLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1))
                        .addComponent(btnBarangMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(panelSidbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSidbarLayout.createSequentialGroup()
                .addGroup(panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDataProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(btnSetting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnDataSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        panelSidbarLayout.setVerticalGroup(
            panelSidbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidbarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnDataProduk)
                .addGap(0, 0, 0)
                .addComponent(btnDataSupplier)
                .addGap(0, 0, 0)
                .addComponent(btnBarangMasuk)
                .addGap(0, 0, 0)
                .addComponent(btnBarangKeluar)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan)
                .addGap(0, 0, 0)
                .addComponent(btnSetting)
                .addGap(0, 0, 0)
                .addComponent(btnAbout)
                .addGap(0, 0, 0)
                .addComponent(jButton9)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidbar, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         int pilihan = JOptionPane.showConfirmDialog(
                null,
                 "Apakah anda yakin ingin keluar", 
                 "Konfirmasi",
                 JOptionPane.YES_NO_OPTION);
       switch (pilihan){
           case JOptionPane.YES_OPTION:
               dispose();
               new FrameLogin().setVisible(true);
               case JOptionPane.NO_OPTION:
               break;
               default:
                   break;
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "about");
        
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "barangMasuk");
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplierActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dataSupplier");
    }//GEN-LAST:event_btnDataSupplierActionPerformed

    private void btnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluarActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "barangKeluar");
    }//GEN-LAST:event_btnBarangKeluarActionPerformed

    private void btnDataProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProdukActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dataProduk");
        
    }//GEN-LAST:event_btnDataProdukActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "laporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "pengaturanAkun");
    }//GEN-LAST:event_btnSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.borderWidth", 0);
            UIManager.put("Component.borderWidth", 0);
            UIManager.put("Button.arc", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FrameDashbord().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(FrameDashbord.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBarangKeluar;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataProduk;
    private javax.swing.JButton btnDataSupplier;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidbar;
    // End of variables declaration//GEN-END:variables
}
